imap_swapi_l3b_combined:
  Instrument_type: Particles (space)
  Data_level: "3b"
  Data_type: L3B_COMBINED>Level-3 Science data
  Logical_source_description: SWAPI Instrument Combined VDF and Differential Flux
