float_fillval: &float_fillval -1.000000e+31
uint4_fillval: &uint4_fillval 4294967295
max_uint16: &max_uint16 65535

data_defaults: &data_defaults
  DEPEND_0: epoch
  VAR_TYPE: data
  FORMAT: F12.6
  FILLVAL: *float_fillval

timeseries_defaults: &timeseries_defaults
  <<: *data_defaults
  DISPLAY_TYPE: time_series

spectrogram_defaults: &spectrogram_defaults
  <<: *data_defaults
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram

support_data_defaults: &support_data_defaults
  <<: *data_defaults
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot

photon_flux:
  <<: *spectrogram_defaults
  CATDESC: Histogram of photon flux in scanning-circle bins
  FIELDNAM: Histogram of photon flux
  LABLAXIS: Flux
  UNITS: Rayleigh
  DELTA_MINUS_VAR: photon_flux_uncertainty
  DELTA_PLUS_VAR: photon_flux_uncertainty
  SCALEMIN: 0
  SCALEMAX: 1000
  SCALETYP: linear
  VALIDMIN: 0.0
  VALIDMAX: 2000.0

photon_flux_uncertainty:
  <<: *support_data_defaults
  DEPEND_1: spin_angle
  CATDESC: Uncertainty of photon flux
  FIELDNAM: Uncertainty of photon flux
  LABLAXIS: Flux Uncertainty
  UNITS: Rayleigh
  VALIDMIN: 0.0
  VALIDMAX: 2000.0

raw_histogram:
  <<: *spectrogram_defaults
  CATDESC: Raw daily counts in lightcurve bins
  FIELDNAM: Raw daily counts
  LABLAXIS: Counts
  FILLVAL: *uint4_fillval
  FORMAT: I10
  UNITS: counts
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 1000000
  VALIDMIN: 0
  VALIDMAX: 1000000


extra_heliospheric_bckgrd:
  <<: *spectrogram_defaults
  CATDESC: Extra-heliospheric background estimate
  FIELDNAM: Extra-heliospheric background
  LABLAXIS: Extra-heliospheric background
  UNITS: Rayleigh
  VALIDMIN: 0.0
  VALIDMAX: 2000.0
  SCALEMIN: 0
  SCALEMAX: 1000
  SCALETYP: linear

time_dependent_bckgrd:
  <<: *spectrogram_defaults
  CATDESC: Time-dependent background estimate
  FIELDNAM: Time-dependent background
  LABLAXIS: Time-dependent background
  UNITS: Rayleigh
  VALIDMIN: 0.0
  VALIDMAX: 2000.0
  SCALEMIN: 0
  SCALEMAX: 1000
  SCALETYP: linear

number_of_bins:
  <<: *support_data_defaults
  CATDESC: Number of histogram bins
  FIELDNAM: Number of histogram bins
  FILLVAL: *max_uint16
  FORMAT: I5
  LABLAXIS: Num of bins
  UNITS: ' '
  VALIDMAX: 3600
  VALIDMIN: 1

exposure_times:
  <<: *spectrogram_defaults
  CATDESC: Exposure time in seconds for GLOWS histogram
  FIELDNAM: Histogram exposure time
  LABLAXIS: Duration
  UNITS: seconds
  VALIDMAX: 4000.0
  VALIDMIN: 0.0
  SCALEMAX: 4000.0
  SCALEMIN: 0.0

epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  DELTA_MINUS_VAR: epoch_delta
  DELTA_PLUS_VAR: epoch_delta
  FILLVAL: 9999-12-31T23:59:59.999999999
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2040-01-01T00:00:00.000000000
  FORMAT: " "
  DISPLAY_TYPE: no_plot

epoch_delta:
  CATDESC: epoch_DELTA
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: epoch_delta
  FILLVAL: -9223372036854775808
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  SCALEMIN: 0
  SCALEMAX: 86000000000000
  SCALETYP: linear
  UNITS: ns
  VAR_TYPE: support_data
  FORMAT: 19I

spin_angle:
  <<: *support_data_defaults
  CATDESC: Spin angle at center of bin in Degrees for GLOWS histogram
  FIELDNAM: Histogram Spin Angle
  LABLAXIS: Spin Angle
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0
  DELTA_PLUS_VAR: spin_angle_delta
  DELTA_MINUS_VAR: spin_angle_delta

spin_angle_delta:
  <<: *support_data_defaults
  CATDESC: Spin angle bin half width in Degrees for GLOWS histogram
  FIELDNAM: Histogram Spin Angle Delta
  LABLAXIS: Spin Angle Delta
  UNITS: degrees
  VALIDMAX: 180.0
  VALIDMIN: 0.0

ecliptic_lat:
  <<: *spectrogram_defaults
  CATDESC: Latitude in ECLIPJ2000 at center of bin in Degrees
  FIELDNAM: Histogram Latitude
  LABLAXIS: Ecliptic Latitude
  UNITS: degrees
  VALIDMAX: 90.0
  VALIDMIN: -90.0
  SCALEMAX: 90.0
  SCALEMIN: -90.0

ecliptic_lon:
  <<: *spectrogram_defaults
  CATDESC: Longitude in ECLIPJ2000 at center of bin in Degrees
  FIELDNAM: Histogram Longitude
  LABLAXIS: Ecliptic Longitude
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: 0.0
  SCALEMAX: 360.0
  SCALEMIN: 0.0

filter_temperature_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged filter temperature
  FIELDNAM: filter temperature average
  LABLAXIS: filter temperature average
  UNITS: Celsius
  VALIDMAX: 1.0
  VALIDMIN: -273.15
  DELTA_PLUS_VAR: filter_temperature_std_dev
  DELTA_MINUS_VAR: filter_temperature_std_dev

filter_temperature_std_dev:
  <<: *support_data_defaults
  CATDESC: standard deviation for filter temperature
  FIELDNAM: filter temperature std dev
  LABLAXIS: filter temperature std dev
  UNITS: Celsius
  VALIDMAX: 1.0
  VALIDMIN: 0.0

hv_voltage_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged channeltron voltage
  FIELDNAM: hv voltage average
  LABLAXIS: hv voltage average
  UNITS: V
  VALIDMAX: 1.0
  VALIDMIN: 0.0
  DELTA_PLUS_VAR: hv_voltage_std_dev
  DELTA_MINUS_VAR: hv_voltage_std_dev

hv_voltage_std_dev:
  <<: *support_data_defaults
  CATDESC: standard deviation for channeltron voltage
  FIELDNAM: hv voltage std dev
  LABLAXIS: hv voltage std dev
  UNITS: V
  VALIDMAX: 1.0
  VALIDMIN: 0.0

spin_period_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged spin period
  FIELDNAM: spin period average
  LABLAXIS: spin period average
  UNITS: s
  VALIDMAX: 1.0
  VALIDMIN: 0.0
  DELTA_PLUS_VAR: spin_period_std_dev
  DELTA_MINUS_VAR: spin_period_std_dev

spin_period_std_dev:
  <<: *support_data_defaults
  CATDESC: standard deviation for spin period
  FIELDNAM: spin period std dev
  LABLAXIS: spin period std dev
  UNITS: s
  VALIDMAX: 1.0
  VALIDMIN: 0.0

spin_period_ground_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged spin period (ground value)
  FIELDNAM: spin period ground average
  LABLAXIS: spin period ground average
  UNITS: s
  VALIDMAX: 1.0
  VALIDMIN: 0.0
  DELTA_PLUS_VAR: spin_period_ground_std_dev
  DELTA_MINUS_VAR: spin_period_ground_std_dev

spin_period_ground_std_dev:
  <<: *support_data_defaults
  CATDESC: standard deviation for spin period (ground value)
  FIELDNAM: spin period ground std dev
  LABLAXIS: spin period ground std dev
  UNITS: s
  VALIDMAX: 1.0
  VALIDMIN: 0.0

pulse_length_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged pulse length
  FIELDNAM: pulse length average
  LABLAXIS: pulse length average
  UNITS: microsecond
  VALIDMAX: 1.0
  VALIDMIN: 0.0
  DELTA_PLUS_VAR: pulse_length_std_dev
  DELTA_MINUS_VAR: pulse_length_std_dev

pulse_length_std_dev:
  <<: *support_data_defaults
  CATDESC: standard deviation for pulse length
  FIELDNAM: pulse length std dev
  LABLAXIS: pulse length std dev
  UNITS: microsecond
  VALIDMAX: 1.0
  VALIDMIN: 0.0

position_angle_offset_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged GLOWS angular offset
  FIELDNAM: position angle offset average
  LABLAXIS: position angle offset average
  UNITS: degrees
  VALIDMAX: 1.0
  VALIDMIN: 0.0
  DELTA_PLUS_VAR: position_angle_offset_std_dev
  DELTA_MINUS_VAR: position_angle_offset_std_dev

position_angle_offset_std_dev:
  <<: *support_data_defaults
  CATDESC: position angle offset standard deviation
  FIELDNAM: position angle offset std dev
  LABLAXIS: position angle offset std dev
  UNITS: degrees
  VALIDMAX: 1.0
  VALIDMIN: 0.0

lon_lat:
  CATDESC: component index for coordinate data
  FORMAT: I10
  VAR_TYPE: metadata

lon_lat_labels:
  CATDESC: label names for coordinate data
  VAR_TYPE: metadata
  FORMAT: A3

spin_axis_orientation_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged spin-axis ecliptic longitude and latitude
  FIELDNAM: spin axis orientation average
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: -90.0
  DELTA_PLUS_VAR: spin_axis_orientation_std_dev
  DELTA_MINUS_VAR: spin_axis_orientation_std_dev
  DEPEND_1: lon_lat
  LABL_PTR_1: lon_lat_labels

spin_axis_orientation_std_dev:
  <<: *support_data_defaults
  CATDESC: Standard deviation for spin-axis longitude and latitude
  FIELDNAM: spin axis orientation std dev
  UNITS: degrees
  VALIDMAX: 360.0
  VALIDMIN: -90.0
  DEPEND_1: lon_lat
  LABL_PTR_1: lon_lat_labels

x_y_z:
  CATDESC: component index for ecliptic coordinate data
  FORMAT: I10
  VAR_TYPE: metadata

x_y_z_labels:
  CATDESC: label names for ecliptic coordinate data
  VAR_TYPE: metadata
  FORMAT: A1

spacecraft_location_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged Cartesian ecliptic coordinates X, Y, Z of IMAP
  FIELDNAM: spacecraft location average
  UNITS: km
  VALIDMAX: 2.0e+8
  VALIDMIN: -2.0e+8
  DELTA_PLUS_VAR: spacecraft_location_std_dev
  DELTA_MINUS_VAR: spacecraft_location_std_dev
  FORMAT: E12.5E1
  DEPEND_1: x_y_z
  LABL_PTR_1: x_y_z_labels


spacecraft_location_std_dev:
  <<: *support_data_defaults
  CATDESC: Standard deviation for ecliptic coordinates of IMAP
  FIELDNAM: spacecraft location std dev
  UNITS: km
  VALIDMAX: 3.0e+6
  VALIDMIN: -3.0e+6
  FORMAT: E12.5E1
  DEPEND_1: x_y_z
  LABL_PTR_1: x_y_z_labels


spacecraft_velocity_average:
  <<: *timeseries_defaults
  CATDESC: Observational-day-averaged values VX, VY, VZ of IMAP velocity components (Cartesian ecliptic frame)
  FIELDNAM: spacecraft velocity average
  UNITS: km/s
  VALIDMAX: 50.0
  VALIDMIN: -50.0
  DELTA_PLUS_VAR: spacecraft_velocity_std_dev
  DELTA_MINUS_VAR: spacecraft_velocity_std_dev
  DEPEND_1: x_y_z
  LABL_PTR_1: x_y_z_labels


spacecraft_velocity_std_dev:
  <<: *support_data_defaults
  CATDESC: standard deviation for velocity components of IMAP
  FIELDNAM: spacecraft velocity std dev
  UNITS: km/s
  VALIDMAX: 1.0
  VALIDMIN: -1.0
  DEPEND_1: x_y_z
  LABL_PTR_1: x_y_z_labels
