epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  FIELDNAM: epoch
  LABLAXIS: epoch
  UNITS: ns
  VALIDMIN: 1990-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid

epoch_delta:
  CATDESC: epoch_delta
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  FIELDNAM: epoch_delta
  LABLAXIS: epoch_delta
  UNITS: ns
  VALIDMIN: 1990-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid

charge:
  CATDESC: charge
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: charge
  LABLAXIS: Charge
  UNITS: MeV
  VALIDMIN: 0
  VALIDMAX: 200
  FILLVAL: -1.00E+31
  SCALETYP: linear

energy:
  CATDESC: energy
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: energy
  LABLAXIS: Energy
  UNITS: MeV
  VALIDMIN: 1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALETYP: log

energy_at_detector:
  CATDESC: energy_at_detector
  VAR_TYPE: data
  DEPEND_0: epoch
  DEPEND_1: detector_id
  DISPLAY_TYPE: no_plot
  FIELDNAM: energy_at_detector
  VALIDMIN: 1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALETYP: log

range:
  CATDESC: range
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: range
  VALIDMIN: 0
  VALIDMAX: 4
  FILLVAL: 255

delta_e:
  CATDESC: delta_e
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: delta_e
  LABLAXIS: Delta E
  UNITS: MeV
  VALIDMIN: 1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALETYP: log

e_prime:
  CATDESC: e_prime
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: e_prime
  LABLAXIS: E Prime
  UNITS: MeV
  VALIDMIN: 1
  VALIDMAX: 10000
  FILLVAL: -1.00E+31
  SCALETYP: log

particle_id:
  CATDESC: particle_id
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: particle_id
  VALIDMIN: 0
  VALIDMAX: 255
  FILLVAL: 65535

priority_buffer_number:
  CATDESC: priority_buffer_number
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: priority_buffer_number
  VALIDMIN: 0
  VALIDMAX: 254
  FILLVAL: 255

latency:
  CATDESC: latency
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: latency
  VALIDMIN: 0
  VALIDMAX: 16
  FILLVAL: 255

stim_tag:
  CATDESC: stim_tag
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: stim_tag
  VALIDMIN: 0
  VALIDMAX: 1

long_event_flag:
  CATDESC: long_event_flag
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: long_event_flag
  VALIDMIN: 0
  VALIDMAX: 1

haz_tag:
  CATDESC: haz_tag
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: haz_tag
  VALIDMIN: 0
  VALIDMAX: 1

a_b_side:
  CATDESC: a_b_side
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: a_b_side
  VALIDMIN: 0
  VALIDMAX: 1

has_unread_flag:
  CATDESC: has_unread_flag
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: has_unread_flag
  VALIDMIN: 0
  VALIDMAX: 1

culling_flag:
  CATDESC: culling_flag
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: culling_flag
  VALIDMIN: 0
  VALIDMAX: 1

pha_value:
  CATDESC: pha_value
  VAR_TYPE: data
  DEPEND_0: epoch
  DEPEND_1: detector_id
  DISPLAY_TYPE: no_plot
  FIELDNAM: pha_value
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535

is_low_gain:
  CATDESC: is_low_gain
  VAR_TYPE: data
  DEPEND_0: epoch
  DEPEND_1: detector_id
  DISPLAY_TYPE: no_plot
  FIELDNAM: is_low_gain
  VALIDMIN: 0
  VALIDMAX: 1

detector_flags:
  CATDESC: detector_flags
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: detector_flags
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535

deindex:
  CATDESC: deindex
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: deindex
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535

epindex:
  CATDESC: epindex
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: epindex
  VALIDMIN: 0
  VALIDMAX: 65534
  FILLVAL: 65535

stim_gain:
  CATDESC: stim_gain
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: stim_gain
  VALIDMIN: 0
  VALIDMAX: 1

a_l_stim:
  CATDESC: a_l_stim
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: a_l_stim
  VALIDMIN: 0
  VALIDMAX: 1

stim_step:
  CATDESC: stim_step
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: stim_step
  VALIDMIN: 0
  VALIDMAX: 254
  FILLVAL: 255

dac_value:
  CATDESC: dac_value
  VAR_TYPE: data
  DEPEND_0: epoch
  DISPLAY_TYPE: no_plot
  FIELDNAM: dac_value
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: 65535

detector_id:
  CATDESC: index of used to support up to 64 detector addresses per event
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  FIELDNAM: detector_id
  VALIDMIN: 0
  VALIDMAX: 64
  FILLVAL: 255

