default_attrs: &default_timeseries
  FORMAT: F19.3
  DEPEND_0: epoch
  FILLVAL: -1.000000e+31
  VALIDMIN: 0
  VALIDMAX: 9223372036854775807
  UNITS: ' '

proton_sw_speed:
  <<: *default_timeseries
  CATDESC: Speed of Proton Solar Wind
  FIELDNAM: proton_sw_speed
  DELTA_MINUS_VAR: proton_sw_speed_delta
  DELTA_PLUS_VAR: proton_sw_speed_delta
  LABLAXIS: Proton Solar Wind Speed
  UNITS: km/s
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

proton_sw_speed_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Speed Uncertainty
  FIELDNAM: proton_sw_speed_delta
  UNITS: km/s

alpha_sw_speed:
  <<: *default_timeseries
  CATDESC: Speed of Alpha Solar Wind
  FIELDNAM: alpha_sw_speed
  DELTA_MINUS_VAR: alpha_sw_speed_delta
  DELTA_PLUS_VAR: alpha_sw_speed_delta
  LABLAXIS: Alpha Solar Wind Speed
  UNITS: km/s
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

alpha_sw_speed_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Alpha Solar Wind Speed Uncertainty
  FIELDNAM: alpha_sw_speed_delta
  UNITS: km/s

epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  DISPLAY_TYPE: 'no_plot'
  DELTA_MINUS_VAR: epoch_delta
  DELTA_PLUS_VAR: epoch_delta
  FILLVAL: 9999-12-31T23:59:59.999999999
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2040-01-01T00:00:00.000000000
  FORMAT: " "

epoch_delta:
  CATDESC: epoch_DELTA
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: epoch_delta
  FILLVAL: -9223372036854775808
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  SCALEMIN: 0
  SCALEMAX: 86000000000000
  SCALETYP: linear
  UNITS: ns
  VAR_TYPE: support_data
  FORMAT: 19I
