default_attrs: &default_timeseries
  FORMAT: F19.3
  DEPEND_0: epoch
  FILLVAL: -1.000000e+31
  VALIDMIN: 0
  VALIDMAX: 9223372036854775807
  UNITS: ' '

proton_sw_speed:
  <<: *default_timeseries
  CATDESC: Speed of Proton Solar Wind
  FIELDNAM: proton_sw_speed
  DELTA_MINUS_VAR: proton_sw_speed_delta
  DELTA_PLUS_VAR: proton_sw_speed_delta
  LABLAXIS: Proton Solar Wind Speed
  UNITS: km/s
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

proton_sw_speed_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Speed Uncertainty
  FIELDNAM: proton_sw_speed_delta
  UNITS: km/s

proton_sw_temperature:
  <<: *default_timeseries
  CATDESC: Temperature of Proton Solar Wind
  FIELDNAM: proton_sw_temperature
  DELTA_MINUS_VAR: proton_sw_temperature_delta
  DELTA_PLUS_VAR: proton_sw_temperature_delta
  LABLAXIS: Proton Solar Wind Temperature
  UNITS: K
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 240000

proton_sw_temperature_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Temperature Uncertainty
  FIELDNAM: proton_sw_temperature_delta
  UNITS: K

proton_sw_density:
  <<: *default_timeseries
  CATDESC: Density of Proton Solar Wind
  FIELDNAM: proton_sw_density
  DELTA_MINUS_VAR: proton_sw_density_delta
  DELTA_PLUS_VAR: proton_sw_density_delta
  LABLAXIS: Proton Solar Wind Density
  UNITS: cm!E-3!N
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 16

proton_sw_density_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Density Uncertainty
  FIELDNAM: proton_sw_density_delta
  UNITS: cm!E-3!N

proton_sw_clock_angle:
  <<: *default_timeseries
  CATDESC: Clock Angle of Proton Solar Wind
  FIELDNAM: proton_sw_clock_angle
  DELTA_MINUS_VAR: proton_sw_clock_angle_delta
  DELTA_PLUS_VAR: proton_sw_clock_angle_delta
  LABLAXIS: Proton Solar Wind Clock Angle
  UNITS: Degrees
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 360

proton_sw_clock_angle_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Clock Angle Uncertainty
  FIELDNAM: proton_sw_clock_angle_delta
  UNITS: Degrees

proton_sw_deflection_angle:
  <<: *default_timeseries
  CATDESC: Deflection Angle of Proton Solar Wind
  FIELDNAM: proton_sw_deflection_angle
  DELTA_MINUS_VAR: proton_sw_deflection_angle_delta
  DELTA_PLUS_VAR: proton_sw_deflection_angle_delta
  LABLAXIS: Proton Solar Wind Deflection Angle
  UNITS: Degrees
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 360

proton_sw_deflection_angle_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Deflection Angle Uncertainty
  FIELDNAM: proton_sw_deflection_angle_delta
  UNITS: Degrees

alpha_sw_speed:
  <<: *default_timeseries
  CATDESC: Speed of Alpha Solar Wind
  FIELDNAM: alpha_sw_speed
  DELTA_MINUS_VAR: alpha_sw_speed_delta
  DELTA_PLUS_VAR: alpha_sw_speed_delta
  LABLAXIS: Alpha Solar Wind Speed
  UNITS: km/s
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

alpha_sw_speed_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Alpha Solar Wind Speed Uncertainty
  FIELDNAM: alpha_sw_speed_delta
  UNITS: km/s

alpha_sw_temperature:
  <<: *default_timeseries
  CATDESC: Temperature of Alpha Solar Wind
  FIELDNAM: alpha_sw_temperature
  DELTA_MINUS_VAR: alpha_sw_temperature_delta
  DELTA_PLUS_VAR: alpha_sw_temperature_delta
  LABLAXIS: Alpha Solar Wind Temperature
  UNITS: K
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 450000

alpha_sw_temperature_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Alpha Solar Wind Temperature Uncertainty
  FIELDNAM: alpha_sw_temperature_delta
  UNITS: K

alpha_sw_density:
  <<: *default_timeseries
  CATDESC: Density of Alpha Solar Wind
  FIELDNAM: alpha_sw_density
  DELTA_MINUS_VAR: alpha_sw_density_delta
  DELTA_PLUS_VAR: alpha_sw_density_delta
  LABLAXIS: Alpha Solar Wind Density
  UNITS: cm!E-3!N
  SCALETYP: linear
  VAR_TYPE: data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 5

alpha_sw_density_delta:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Alpha Solar Wind Density Uncertainty
  FIELDNAM: alpha_sw_density_delta
  UNITS: cm!E-3!N


epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  DELTA_MINUS_VAR: epoch_delta
  DELTA_PLUS_VAR: epoch_delta
  FILLVAL: 9999-12-31T23:59:59.999999999
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2040-01-01T00:00:00.000000000
  FORMAT: " "

epoch_delta:
  CATDESC: epoch_DELTA
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: epoch_delta
  FILLVAL: -9223372036854775808
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  SCALEMIN: 0
  SCALEMAX: 86000000000000
  SCALETYP: linear
  UNITS: ns
  VAR_TYPE: support_data
  FORMAT: 19I
