float_fillval: &float_fillval -1.000000e+31
max_uint16: &max_uint16 65535


bins:
  VALIDMIN: 0
  VALIDMAX: 3599
  CATDESC: Histogram bin number
  FIELDNAM: Bin number
  FORMAT: I5
  VAR_TYPE: support_data
  LABLAXIS: Bin Number
  FILLVAL: -32768
  UNITS: ' '
  MONOTON: INCREASE
  SCALETYP: linear

support_data_defaults: &support_data_defaults
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  VAR_TYPE: support_data
  FORMAT: I10
  RESOLUTION: ISO8601

photon_flux:
  VALIDMIN: 0.0
  VALIDMAX: 2000.0
  CATDESC: Histogram of photon flux in scanning-circle bins
  DEPEND_0: epoch
  DEPEND_1: spin_angle
  DELTA_MINUS_VAR: photon_flux_uncertainty
  DELTA_PLUS_VAR: photon_flux_uncertainty
  FIELDNAM: Histogram of photon flux
  FORMAT: F12.6
  DISPLAY_TYPE: spectrogram
  SCALEMIN: 0
  SCALEMAX: 1000
  SCALETYP: linear
  LABLAXIS: Flux
  FILLVAL: *float_fillval
  UNITS: Rayleigh
  VAR_TYPE: data

photon_flux_uncertainty:
  VALIDMIN: 0.0
  VALIDMAX: 2000.0
  CATDESC: Uncertainty of photon flux
  DEPEND_0: epoch
  DEPEND_1: bins
  FIELDNAM: Uncertainty of photon flux
  LABLAXIS: Flux Uncertainty
  FORMAT: F12.6
  FILLVAL: *float_fillval
  UNITS: Rayleigh
  VAR_TYPE: support_data

number_of_bins:
  <<: *support_data_defaults
  CATDESC: Number of histogram bins
  FIELDNAM: Number of histogram bins
  FILLVAL: *max_uint16
  FORMAT: I5
  LABLAXIS: Num of bins
  UNITS: ' '
  VALIDMAX: 3600
  VALIDMIN: 1

exposure_times:
  <<: *support_data_defaults
  CATDESC: Exposure time in seconds for GLOWS histogram
  FIELDNAM: Histogram exposure time
  FILLVAL: *float_fillval
  FORMAT: F12.6
  UNITS: seconds
  LABLAXIS: Duration
  VALIDMAX: 4000.0
  VALIDMIN: 0.0

epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  DELTA_MINUS_VAR: epoch_delta
  DELTA_PLUS_VAR: epoch_delta
  FILLVAL: 9999-12-31T23:59:59.999999999
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2040-01-01T00:00:00.000000000
  FORMAT: " "



epoch_delta:
  CATDESC: epoch_DELTA
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: epoch_delta
  FILLVAL: -9223372036854775808
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  SCALEMIN: 0
  SCALEMAX: 86000000000000
  SCALETYP: linear
  UNITS: ns
  VAR_TYPE: support_data
  FORMAT: 19I


spin_angle:
  <<: *support_data_defaults
  CATDESC: Spin angle at center of bin in Degrees for GLOWS histogram
  FIELDNAM: Histogram Spin Angle time
  FILLVAL: *float_fillval
  FORMAT: F12.6
  UNITS: degrees
  LABLAXIS: Spin Angle
  VALIDMAX: 360.0
  VALIDMIN: 0.0

