Descriptor: SWAPI>The Solar Wind and Pickup Ion
TEXT: >
  The Solar Wind and Pickup Ion (SWAPI) instrument measures several different
  elements of the solar wind, including hydrogen (H) and helium (He) ions,
  and, on occasion, heavy ions produced by large events from the Sun. See
  https://imap.princeton.edu/instruments/swapi for more details. SWAPI level-1
  data contains primary, secondary, coincidence counts per ESA voltage step and
  time. Level-2 data contains the same data as level-1 but counts are converted
  to rates by dividing counts by time. Level-3 data contains
Instrument_type: Particles (space)
