Instrument_type: Particles (space)
Data_level: "3"
Data_type: L3_SCI>Level-3 Science data
Logical_file_id: imap_swapi_l3_proton-solar-wind-speed
Logical_source: imap_swapi_l3_proton-solar-wind-speed
Logical_source_description: SWAPI Instrument Proton Solar Wind Speed
