FROM python:3.12-slim
RUN apt-get update && apt-get install -y git libgfortran5
RUN pip install --upgrade pip
RUN mkdir temp_cdf_data
RUN mkdir -p /mnt/spice
RUN mkdir -p /spice_kernels
RUN mkdir -p /run_local_input_data
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY spice_kernels spice_kernels
COPY imap_l3_processing imap_l3_processing
COPY scripts scripts
COPY imap_l3_data_processor.py .
COPY tests tests
COPY instrument_team_data instrument_team_data
COPY imap_l3_processing/glows/l3e/l3e_toolkit/survProbHi survProbHi
COPY imap_l3_processing/glows/l3e/l3e_toolkit/survProbLo survProbLo
COPY imap_l3_processing/glows/l3e/l3e_toolkit/survProbUltra survProbUltra
RUN chmod +x survProbHi
RUN chmod +x survProbLo
RUN chmod +x survProbUltra
COPY run_local.py .
ENV IN_GLOWS_INTEGRATION_DOCKER = "set"
ENV PYTHONPATH=$PYTHONPATH:/imap_l3_processing
ENTRYPOINT ["python", "-m", "unittest"]