from datetime import timedelta
from unittest import TestCase
from unittest.mock import sentinel

import numpy as np
from spacepy import pycdf

from imap_l3_processing.hit.l3.sectored_products.models import HitPitchAngleDataProduct
from imap_l3_processing.models import DataProductVariable


class TestHitPitchAngleDataProduct(TestCase):
    def test_to_data_product_variables(self):
        epoch_deltas = np.array([timedelta(seconds=5)])

        data = HitPitchAngleDataProduct(sentinel.input_meta_data,
                                        sentinel.epochs,
                                        epoch_deltas,
                                        sentinel.pitch_angles,
                                        sentinel.pitch_angles_deltas,
                                        sentinel.gyrophases,
                                        sentinel.gyrophase_deltas,
                                        sentinel.h_intensity,
                                        sentinel.h_intensity_delta_plus,
                                        sentinel.h_intensity_delta_minus,
                                        sentinel.h_pa_intensity,
                                        sentinel.h_pa_intensity_delta_plus,
                                        sentinel.h_pa_intensity_delta_minus,
                                        sentinel.h_energies,
                                        sentinel.h_energy_delta_plus,
                                        sentinel.h_energy_delta_minus,
                                        sentinel.he4_intensity,
                                        sentinel.he4_intensity_delta_plus,
                                        sentinel.he4_intensity_delta_minus,
                                        sentinel.he4_pa_intensity,
                                        sentinel.he4_pa_intensity_delta_plus,
                                        sentinel.he4_pa_intensity_delta_minus,
                                        sentinel.he4_energies,
                                        sentinel.he4_energy_delta_plus,
                                        sentinel.he4_energy_delta_minus,
                                        sentinel.cno_intensity,
                                        sentinel.cno_intensity_delta_plus,
                                        sentinel.cno_intensity_delta_minus,
                                        sentinel.cno_pa_intensity,
                                        sentinel.cno_pa_intensity_delta_plus,
                                        sentinel.cno_pa_intensity_delta_minus,
                                        sentinel.cno_energies,
                                        sentinel.cno_energy_delta_plus,
                                        sentinel.cno_energy_delta_minus,
                                        sentinel.ne_mg_si_intensity,
                                        sentinel.ne_mg_si_intensity_delta_plus,
                                        sentinel.ne_mg_si_intensity_delta_minus,
                                        sentinel.ne_mg_si_pa_intensity,
                                        sentinel.ne_mg_si_pa_intensity_delta_plus,
                                        sentinel.ne_mg_si_pa_intensity_delta_minus,
                                        sentinel.ne_mg_si_energies,
                                        sentinel.ne_mg_si_energy_delta_plus,
                                        sentinel.ne_mg_si_energy_delta_minus,
                                        sentinel.iron_intensity,
                                        sentinel.iron_intensity_delta_plus,
                                        sentinel.iron_intensity_delta_minus,
                                        sentinel.iron_pa_intensity,
                                        sentinel.iron_pa_intensity_delta_plus,
                                        sentinel.iron_pa_intensity_delta_minus,
                                        sentinel.iron_energies,
                                        sentinel.iron_energy_delta_plus,
                                        sentinel.iron_energy_delta_minus,
                                        sentinel.measurement_pitch_angle,
                                        sentinel.measurement_gyrophase
                                        )

        data_product_variables = data.to_data_product_variables()
        expected_epoch_deltas = np.array([5e9])
        expected_data_product_variables = [
            DataProductVariable("epoch", sentinel.epochs, cdf_data_type=pycdf.const.CDF_TIME_TT2000),
            DataProductVariable("epoch_delta", expected_epoch_deltas, cdf_data_type=pycdf.const.CDF_INT8),
            DataProductVariable("pitch_angle", sentinel.pitch_angles, record_varying=False),
            DataProductVariable("pitch_angle_delta", sentinel.pitch_angles_deltas, record_varying=False),
            DataProductVariable("gyrophase", sentinel.gyrophases, record_varying=False),
            DataProductVariable("gyrophase_delta", sentinel.gyrophase_deltas, record_varying=False),
            DataProductVariable("h_intensity", sentinel.h_intensity),
            DataProductVariable("h_intensity_delta_plus", sentinel.h_intensity_delta_plus),
            DataProductVariable("h_intensity_delta_minus", sentinel.h_intensity_delta_minus),
            DataProductVariable("h_intensity_pa", sentinel.h_pa_intensity),
            DataProductVariable("h_intensity_pa_delta_plus", sentinel.h_pa_intensity_delta_plus),
            DataProductVariable("h_intensity_pa_delta_minus", sentinel.h_pa_intensity_delta_minus),
            DataProductVariable("h_energy", sentinel.h_energies, record_varying=False),
            DataProductVariable("h_energy_delta_plus", sentinel.h_energy_delta_plus, record_varying=False),
            DataProductVariable("h_energy_delta_minus", sentinel.h_energy_delta_minus, record_varying=False),
            DataProductVariable("he4_intensity", sentinel.he4_intensity),
            DataProductVariable("he4_intensity_delta_plus", sentinel.he4_intensity_delta_plus),
            DataProductVariable("he4_intensity_delta_minus", sentinel.he4_intensity_delta_minus),
            DataProductVariable("he4_intensity_pa", sentinel.he4_pa_intensity),
            DataProductVariable("he4_intensity_pa_delta_plus", sentinel.he4_pa_intensity_delta_plus),
            DataProductVariable("he4_intensity_pa_delta_minus", sentinel.he4_pa_intensity_delta_minus),
            DataProductVariable("he4_energy", sentinel.he4_energies, record_varying=False),
            DataProductVariable("he4_energy_delta_plus", sentinel.he4_energy_delta_plus, record_varying=False),
            DataProductVariable("he4_energy_delta_minus", sentinel.he4_energy_delta_minus, record_varying=False),
            DataProductVariable("cno_intensity", sentinel.cno_intensity),
            DataProductVariable("cno_intensity_delta_plus", sentinel.cno_intensity_delta_plus),
            DataProductVariable("cno_intensity_delta_minus", sentinel.cno_intensity_delta_minus),
            DataProductVariable("cno_intensity_pa", sentinel.cno_pa_intensity),
            DataProductVariable("cno_intensity_pa_delta_plus", sentinel.cno_pa_intensity_delta_plus),
            DataProductVariable("cno_intensity_pa_delta_minus", sentinel.cno_pa_intensity_delta_minus),
            DataProductVariable("cno_energy", sentinel.cno_energies, record_varying=False),
            DataProductVariable("cno_energy_delta_plus", sentinel.cno_energy_delta_plus, record_varying=False),
            DataProductVariable("cno_energy_delta_minus", sentinel.cno_energy_delta_minus, record_varying=False),
            DataProductVariable("nemgsi_intensity", sentinel.ne_mg_si_intensity),
            DataProductVariable("nemgsi_intensity_delta_plus", sentinel.ne_mg_si_intensity_delta_plus),
            DataProductVariable("nemgsi_intensity_delta_minus", sentinel.ne_mg_si_intensity_delta_minus),
            DataProductVariable("nemgsi_intensity_pa", sentinel.ne_mg_si_pa_intensity),
            DataProductVariable("nemgsi_intensity_pa_delta_plus", sentinel.ne_mg_si_pa_intensity_delta_plus),
            DataProductVariable("nemgsi_intensity_pa_delta_minus", sentinel.ne_mg_si_pa_intensity_delta_minus),
            DataProductVariable("nemgsi_energy", sentinel.ne_mg_si_energies, record_varying=False),
            DataProductVariable("nemgsi_energy_delta_plus", sentinel.ne_mg_si_energy_delta_plus, record_varying=False),
            DataProductVariable("nemgsi_energy_delta_minus", sentinel.ne_mg_si_energy_delta_minus,
                                record_varying=False),
            DataProductVariable("fe_intensity", sentinel.iron_intensity),
            DataProductVariable("fe_intensity_delta_plus", sentinel.iron_intensity_delta_plus),
            DataProductVariable("fe_intensity_delta_minus", sentinel.iron_intensity_delta_minus),
            DataProductVariable("fe_intensity_pa", sentinel.iron_pa_intensity),
            DataProductVariable("fe_intensity_pa_delta_plus", sentinel.iron_pa_intensity_delta_plus),
            DataProductVariable("fe_intensity_pa_delta_minus", sentinel.iron_pa_intensity_delta_minus),
            DataProductVariable("fe_energy", sentinel.iron_energies, record_varying=False),
            DataProductVariable("fe_energy_delta_plus", sentinel.iron_energy_delta_plus, record_varying=False),
            DataProductVariable("fe_energy_delta_minus", sentinel.iron_energy_delta_minus, record_varying=False),
            DataProductVariable("measurement_pitch_angle", sentinel.measurement_pitch_angle),
            DataProductVariable("measurement_gyrophase", sentinel.measurement_gyrophase),
        ]

        self.assertEqual(expected_data_product_variables, data_product_variables)
