from datetime import timedelta
from unittest import TestCase
from unittest.mock import sentinel

import numpy as np
from spacepy import pycdf

from imap_processing.hit.l3.sectored_products.models import HitPitchAngleDataProduct
from imap_processing.models import DataProductVariable


class TestHitPitchAngleDataProduct(TestCase):
    def test_to_data_product_variables(self):
        epoch_deltas = np.array([timedelta(seconds=5)])

        data = HitPitchAngleDataProduct(sentinel.input_meta_data,
                                        sentinel.epochs,
                                        epoch_deltas,
                                        sentinel.pitch_angles,
                                        sentinel.pitch_angles_deltas,
                                        sentinel.gyrophases,
                                        sentinel.gyrophase_deltas,
                                        sentinel.h_fluxes,
                                        sentinel.h_flux_delta_plus,
                                        sentinel.h_flux_delta_minus,
                                        sentinel.h_pa_fluxes,
                                        sentinel.h_pa_fluxes_delta_plus,
                                        sentinel.h_pa_fluxes_delta_minus,
                                        sentinel.h_energies,
                                        sentinel.h_energy_delta_plus,
                                        sentinel.h_energy_delta_minus,
                                        sentinel.he4_fluxes,
                                        sentinel.he4_flux_delta_plus,
                                        sentinel.he4_flux_delta_minus,
                                        sentinel.he4_pa_fluxes,
                                        sentinel.he4_pa_fluxes_delta_plus,
                                        sentinel.he4_pa_fluxes_delta_minus,
                                        sentinel.he4_energies,
                                        sentinel.he4_energy_delta_plus,
                                        sentinel.he4_energy_delta_minus,
                                        sentinel.cno_fluxes,
                                        sentinel.cno_flux_delta_plus,
                                        sentinel.cno_flux_delta_minus,
                                        sentinel.cno_pa_fluxes,
                                        sentinel.cno_pa_fluxes_delta_plus,
                                        sentinel.cno_pa_fluxes_delta_minus,
                                        sentinel.cno_energies,
                                        sentinel.cno_energy_delta_plus,
                                        sentinel.cno_energy_delta_minus,
                                        sentinel.ne_mg_si_fluxes,
                                        sentinel.ne_mg_si_flux_delta_plus,
                                        sentinel.ne_mg_si_flux_delta_minus,
                                        sentinel.ne_mg_si_pa_fluxes,
                                        sentinel.ne_mg_si_pa_fluxes_delta_plus,
                                        sentinel.ne_mg_si_pa_fluxes_delta_minus,
                                        sentinel.ne_mg_si_energies,
                                        sentinel.ne_mg_si_energy_delta_plus,
                                        sentinel.ne_mg_si_energy_delta_minus,
                                        sentinel.iron_fluxes,
                                        sentinel.iron_flux_delta_plus,
                                        sentinel.iron_flux_delta_minus,
                                        sentinel.iron_pa_fluxes,
                                        sentinel.iron_pa_fluxes_delta_plus,
                                        sentinel.iron_pa_fluxes_delta_minus,
                                        sentinel.iron_energies,
                                        sentinel.iron_energy_delta_plus,
                                        sentinel.iron_energy_delta_minus
                                        )

        data_product_variables = data.to_data_product_variables()
        expected_epoch_deltas = np.array([5e9])
        expected_data_product_variables = [
            DataProductVariable("epoch", sentinel.epochs, cdf_data_type=pycdf.const.CDF_TIME_TT2000),
            DataProductVariable("epoch_delta", expected_epoch_deltas, cdf_data_type=pycdf.const.CDF_INT8),
            DataProductVariable("pitch_angle", sentinel.pitch_angles, record_varying=False),
            DataProductVariable("pitch_angle_delta", sentinel.pitch_angles_deltas, record_varying=False),
            DataProductVariable("gyrophase", sentinel.gyrophases, record_varying=False),
            DataProductVariable("gyrophase_delta", sentinel.gyrophase_deltas, record_varying=False),
            DataProductVariable("h_flux", sentinel.h_fluxes),
            DataProductVariable("h_flux_delta_plus", sentinel.h_flux_delta_plus),
            DataProductVariable("h_flux_delta_minus", sentinel.h_flux_delta_minus),
            DataProductVariable("h_flux_pa", sentinel.h_pa_fluxes),
            DataProductVariable("h_flux_pa_delta_plus", sentinel.h_pa_fluxes_delta_plus),
            DataProductVariable("h_flux_pa_delta_minus", sentinel.h_pa_fluxes_delta_minus),
            DataProductVariable("h_energy", sentinel.h_energies, record_varying=False),
            DataProductVariable("h_energy_delta_plus", sentinel.h_energy_delta_plus, record_varying=False),
            DataProductVariable("h_energy_delta_minus", sentinel.h_energy_delta_minus, record_varying=False),
            DataProductVariable("he4_flux", sentinel.he4_fluxes),
            DataProductVariable("he4_flux_delta_plus", sentinel.he4_flux_delta_plus),
            DataProductVariable("he4_flux_delta_minus", sentinel.he4_flux_delta_minus),
            DataProductVariable("he4_flux_pa", sentinel.he4_pa_fluxes),
            DataProductVariable("he4_flux_pa_delta_plus", sentinel.he4_pa_fluxes_delta_plus),
            DataProductVariable("he4_flux_pa_delta_minus", sentinel.he4_pa_fluxes_delta_minus),
            DataProductVariable("he4_energy", sentinel.he4_energies, record_varying=False),
            DataProductVariable("he4_energy_delta_plus", sentinel.he4_energy_delta_plus, record_varying=False),
            DataProductVariable("he4_energy_delta_minus", sentinel.he4_energy_delta_minus, record_varying=False),
            DataProductVariable("cno_flux", sentinel.cno_fluxes),
            DataProductVariable("cno_flux_delta_plus", sentinel.cno_flux_delta_plus),
            DataProductVariable("cno_flux_delta_minus", sentinel.cno_flux_delta_minus),
            DataProductVariable("cno_flux_pa", sentinel.cno_pa_fluxes),
            DataProductVariable("cno_flux_pa_delta_plus", sentinel.cno_pa_fluxes_delta_plus),
            DataProductVariable("cno_flux_pa_delta_minus", sentinel.cno_pa_fluxes_delta_minus),
            DataProductVariable("cno_energy", sentinel.cno_energies, record_varying=False),
            DataProductVariable("cno_energy_delta_plus", sentinel.cno_energy_delta_plus, record_varying=False),
            DataProductVariable("cno_energy_delta_minus", sentinel.cno_energy_delta_minus, record_varying=False),
            DataProductVariable("nemgsi_flux", sentinel.ne_mg_si_fluxes),
            DataProductVariable("nemgsi_flux_delta_plus", sentinel.ne_mg_si_flux_delta_plus),
            DataProductVariable("nemgsi_flux_delta_minus", sentinel.ne_mg_si_flux_delta_minus),
            DataProductVariable("nemgsi_flux_pa", sentinel.ne_mg_si_pa_fluxes),
            DataProductVariable("nemgsi_flux_pa_delta_plus", sentinel.ne_mg_si_pa_fluxes_delta_plus),
            DataProductVariable("nemgsi_flux_pa_delta_minus", sentinel.ne_mg_si_pa_fluxes_delta_minus),
            DataProductVariable("nemgsi_energy", sentinel.ne_mg_si_energies, record_varying=False),
            DataProductVariable("nemgsi_energy_delta_plus", sentinel.ne_mg_si_energy_delta_plus, record_varying=False),
            DataProductVariable("nemgsi_energy_delta_minus", sentinel.ne_mg_si_energy_delta_minus,
                                record_varying=False),
            DataProductVariable("fe_flux", sentinel.iron_fluxes),
            DataProductVariable("fe_flux_delta_plus", sentinel.iron_flux_delta_plus),
            DataProductVariable("fe_flux_delta_minus", sentinel.iron_flux_delta_minus),
            DataProductVariable("fe_flux_pa", sentinel.iron_pa_fluxes),
            DataProductVariable("fe_flux_pa_delta_plus", sentinel.iron_pa_fluxes_delta_plus),
            DataProductVariable("fe_flux_pa_delta_minus", sentinel.iron_pa_fluxes_delta_minus),
            DataProductVariable("fe_energy", sentinel.iron_energies, record_varying=False),
            DataProductVariable("fe_energy_delta_plus", sentinel.iron_energy_delta_plus, record_varying=False),
            DataProductVariable("fe_energy_delta_minus", sentinel.iron_energy_delta_minus, record_varying=False),
        ]

        self.assertEqual(expected_data_product_variables, data_product_variables)
