GLOWS_L2_DESCRIPTOR = "hist"
GLOWS_CALIBRATION_DATA_DESCRIPTOR = "calibration-data"
GLOWS_TIME_DEPENDENT_BACKGROUND_DESCRIPTOR = "time-dep-bckgrd"
GLOWS_EXTRA_HELIOSPHERIC_BACKGROUND_DESCRIPTOR = "map-of-extra-helio-bckgrd"
GLOWS_PIPELINE_SETTINGS_DESCRIPTOR = "pipeline-settings"

GLOWS_L3A_DESCRIPTOR = "hist"
GLOWS_L3D_DESCRIPTOR = 'solar-hist'

GLOWS_L3E_ULTRA_SF_DESCRIPTOR = 'survival-probability-ul-sf'
GLOWS_L3E_ULTRA_HF_DESCRIPTOR = 'survival-probability-ul-hf'
