from datetime import date

import numpy as np

POST_ACCELERATION_VOLTAGE_IN_KV = 15
ENERGY_LOST_IN_CARBON_FOIL = 0
CONVERSION_CONSTANT_K = 1.692e-5

CONSTANT_C_FROM_INSTRUMENT_TEAM = 2.283e-8
AZIMUTH_STEP_SIZE = np.deg2rad(15)
ELEVATION_STEP_SIZE = np.deg2rad(15)
ENERGY_STEP_SIZE = 0.4

CODICE_LO_NUM_AZIMUTH_BINS = 24
CODICE_LO_NUM_ESA_STEPS = 128
CODICE_LO_NUM_SPIN_SECTORS = 24

CODICE_INSTRUMENT_TO_SC_FRAME_SPIN_ANGLE_OFFSET = 46.0

CODICE_SECOND_ERA = date(2025, 11, 24)
CODICE_THIRD_ERA = date(2026, 1, 29)