import numpy as np

POST_ACCELERATION_VOLTAGE_IN_KV = 15
ENERGY_LOST_IN_CARBON_FOIL = 0
CONVERSION_CONSTANT_K = 1.692e-5

AZIMUTH_STEP_SIZE = np.deg2rad(30)
ELEVATION_STEP_SIZE = np.deg2rad(30)
ENERGY_STEP_SIZE = 100

CODICE_LO_NUM_AZIMUTH_BINS = 24
CODICE_LO_NUM_ESA_STEPS = 128

CODICE_SPIN_ANGLE_OFFSET_FROM_MAG_BOOM = 316.0
