GLOWS_L2_DESCRIPTOR = "histogram-"
GLOWS_CALIBRATION_DATA_DESCRIPTOR = "calibration-data-text-not-cdf"
GLOWS_TIME_DEPENDENT_BACKGROUND_DESCRIPTOR = "time-dep-bckgrd-text-not-cdf"
GLOWS_EXTRA_HELIOSPHERIC_BACKGROUND_DESCRIPTOR = "map-of-extra-helio-bckgrd-text-not-cdf"
GLOWS_PIPELINE_SETTINGS_DESCRIPTOR = "pipeline-settings-json-not-cdf"
