GLOWS_L2_DESCRIPTOR = "histogram-"
GLOWS_NUMBER_OF_BINS_ANCILLARY_DESCRIPTOR = "histogram-number-of-bins-text-not-cdf"
GLOWS_TIME_DEPENDENT_BACKGROUND_DESCRIPTOR = "histogram-background-estimate-text-not-cdf"
GLOWS_TIME_INDEPENDENT_BACKGROUND_DESCRIPTOR = "histogram-time-independent-background-map-text-not-cdf"
GLOWS_BAD_ANGLE_FLAG_CONFIG_DESCRIPTOR = "histogram-bad-angle-flags-configuration-json-not-cdf"
