imap_hi_l3_spectral-fit-index:
  Data_level: 3
  Data_type: L3_SFI>Level-3 Spectral Fit Index
  Logical_source: imap_hi_l3_spectral-fit-index
  Logical_source_description: IMAP-Hi Instrument Level-3 Spectral Fit Index.

imap_hi_l3_45sensor-spacecraft-survival-full-4deg-map:
  Data_level: "3"
  Data_type: L3_45sensor-spacecraft-survival-full-4deg-map>Level-3 Survival Corrected Full 4 degree
  Logical_source: imap_hi_l3_45sensor-spacecraft-survival-full-4deg-map
  Logical_source_description: IMAP-Hi Instrument Level-3 Survival Corrected Full 4 degree