epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: J2000 Nanoseconds
  FORMAT: ' '
  LABLAXIS: epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2059-12-31T23:59:58.999000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  CATDESC: Epoch delta
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch Delta
  FORMAT: I19
  LABLAXIS: Epoch delta
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 31536000000000000
  FILLVAL: -9223372036854775808
energy:
  NAME: energy
  DATA_TYPE: CDF_REAL4
  CATDESC: energy
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy
  FORMAT: F6.2
  LABLAXIS: Energy
  UNITS: keV
  VALIDMIN: 0.0
  VALIDMAX: 10000.0
  FILLVAL: -1.00E+31
  DELTA_PLUS_VAR: energy_delta_plus
  DELTA_MINUS_VAR: energy_delta_minus
  MONOTON: INCREASE
energy_label:
  NAME: energy_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label variable for energy coordinate
  DEPEND_1: energy
  VAR_TYPE: metadata
  FIELDNAM: Energy Label
  FORMAT: A16
  FILLVAL: ' '
energy_delta_minus:
  NAME: energy_delta_minus
  DATA_TYPE: CDF_REAL4
  CATDESC: Lower bound of energy range
  DEPEND_1: energy
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy Delta Minus
  FORMAT: F6.2
  LABLAXIS: Energy delta minus
  UNITS: keV
  VALIDMIN: 0.0
  VALIDMAX: 100.0
  FILLVAL: -1.00E+31
energy_delta_plus:
  NAME: energy_delta_plus
  DATA_TYPE: CDF_REAL4
  CATDESC: Upper bound of energy range
  DEPEND_1: energy
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy Delta Plus
  FORMAT: F6.2
  LABLAXIS: Energy delta plus
  UNITS: keV
  VALIDMIN: 0.0
  VALIDMAX: 100.0
  FILLVAL: -1.00E+31
pixel_index:
  NAME: pixel_index
  DATA_TYPE: CDF_INT8
  CATDESC: Index of HEALPix array
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: HEALPix Index
  FORMAT: I8
  LABLAXIS: HEALPix index
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 12582912
  FILLVAL: -9223372036854775808
  LABL_PTR_1: pixel_index_label
  MONOTON: INCREASE
pixel_index_label:
  NAME: pixel_index_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label variable for HEALPix index
  DEPEND_1: pixel_index
  VAR_TYPE: metadata
  FIELDNAM: Label Variable For HEALPix Index
  FORMAT: A16
  FILLVAL: ' '
latitude:
  NAME: latitude
  DATA_TYPE: CDF_REAL4
  CATDESC: Pixel center latitude
  VAR_TYPE: metadata
  RECORD_VARYING: NRV
  FIELDNAM: HAE Latitude
  FORMAT: F6.1
  LABLAXIS: Latitude
  UNITS: degrees
  VALIDMIN: -90.0
  VALIDMAX: 90.0
  FILLVAL: -1.00E+31
  MONOTON: INCREASE
longitude:
  NAME: longitude
  DATA_TYPE: CDF_REAL4
  CATDESC: Pixel center longitude
  VAR_TYPE: metadata
  RECORD_VARYING: NRV
  FIELDNAM: HAE Longitude
  FORMAT: F6.1
  LABLAXIS: Longitude
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0
  FILLVAL: -1.00E+31
  MONOTON: INCREASE
ena_intensity:
  NAME: ena_intensity
  DATA_TYPE: CDF_REAL4
  CATDESC: Survival probability corrected ENA intensity
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pixel_index
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: image
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Intensity
  FORMAT: F12.1
  LABLAXIS: Intensity
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: pixel_index_label
  DELTA_PLUS_VAR: ena_intensity_stat_unc
  DELTA_MINUS_VAR: ena_intensity_stat_unc
ena_intensity_stat_unc:
  NAME: ena_intensity_stat_unc
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA intensity statistical uncertainty
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pixel_index
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Intensity Stat Unc
  FORMAT: F12.1
  LABLAXIS: Statistical unc.
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: pixel_index_label
ena_intensity_sys_err:
  NAME: ena_intensity_sys_err
  DATA_TYPE: CDF_REAL4
  CATDESC: ENA intensity systematic uncertainty.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pixel_index
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Intensity Uncertainty
  FORMAT: F12.1
  LABLAXIS: Uncertainty
  UNITS: cm -2 s -1 sr -1 keV -1
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: pixel_index_label
exposure_factor:
  NAME: exposure_factor
  DATA_TYPE: CDF_REAL4
  CATDESC: Exact or approximate exposure time over which counts in a pixel are accumulated.  Used as a weighting factor for combining data quantities sensibly.
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pixel_index
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: no_plot
  VARIABLE_PURPOSE: ' '
  FIELDNAM: Exposure Times
  FORMAT: F12.1
  LABLAXIS: Exposure
  UNITS: s
  VALIDMIN: 0.0
  VALIDMAX: 1.00E+9
  FILLVAL: -1.00E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: pixel_index_label
obs_date:
  NAME: obs_date
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Mean collection date of data in a pixel
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pixel_index
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: image
  VARIABLE_PURPOSE: ' '
  FIELDNAM: J2000 Nanoseconds
  FORMAT: ' '
  LABLAXIS: epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2059-12-31T23:59:58.999000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  LABL_PTR_1: energy_label
  LABL_PTR_2: pixel_index_label
obs_date_range:
  NAME: obs_date_range
  DATA_TYPE: CDF_INT8
  CATDESC: Standard deviation of the observation date
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pixel_index
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: image
  VARIABLE_PURPOSE: ' '
  FIELDNAM: J2000 Nanoseconds
  FORMAT: I19
  LABLAXIS: epoch
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 31536000000000000
  FILLVAL: -9223372036854775808
  LABL_PTR_1: energy_label
  LABL_PTR_2: pixel_index_label
solid_angle:
  NAME: solid_angle
  DATA_TYPE: CDF_REAL4
  CATDESC: Solid angle of subtended by each pixel
  DEPEND_1: pixel_index
  VAR_TYPE: data
  RECORD_VARYING: NRV
  DISPLAY_TYPE: image
  FIELDNAM: Solid Angle
  VARIABLE_PURPOSE: ' '
  FORMAT: F6.2
  LABLAXIS: Solid Angle
  UNITS: sr
  VALIDMIN: 0.0
  VALIDMAX: 12.56637061
  FILLVAL: -1.00E+31
  LABL_PTR_1: pixel_index_label