epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  DATA_TYPE: CDF_INT8
  CATDESC: Epoch delta
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch Delta
  FORMAT: I19
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 600000000000
  FILLVAL: -9223372036854775808
  SCALETYP: linear
  LABLAXIS: Epoch delta
  DEPEND_0: epoch
combined_energy:
  NAME: combined_energy
  DATA_TYPE: CDF_REAL4
  CATDESC: Combined solar wind energy
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Combined Solar Wind Energy
  FORMAT: F19.3
  LABLAXIS: Combined SW energy
  UNITS: eV/q
  VALIDMIN: 0
  VALIDMAX: 21500
  FILLVAL: -1.000000e+31
  SCALETYP: log
  DELTA_PLUS_VAR: combined_energy_stat_uncert_plus
  DELTA_MINUS_VAR: combined_energy_stat_uncert_minus
  SCALEMIN: 100
  SCALEMAX: 20000
combined_energy_stat_uncert_minus:
  NAME: combined_energy_stat_uncert_minus
  DATA_TYPE: CDF_REAL4
  CATDESC: Combined solar wind energy uncertainty minus
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Combined Solar Wind Energy Uncertainty Minus
  FORMAT: F19.3
  LABLAXIS: Combined SW energy uncertainty minus
  UNITS: eV/q
  VALIDMIN: 0
  VALIDMAX: 2000
  FILLVAL: -1.000000e+31
combined_energy_stat_uncert_plus:
  NAME: combined_energy_stat_uncert_plus
  DATA_TYPE: CDF_REAL4
  CATDESC: Combined solar wind energy uncertainty plus
  DEPEND_0: epoch
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Combined Solar Wind Energy Uncertainty Plus
  FORMAT: F19.3
  LABLAXIS: Combined energy SW uncertainty plus
  UNITS: eV/q
  VALIDMIN: 0
  VALIDMAX: 2000
  FILLVAL: -1.000000e+31
combined_differential_flux:
  NAME: combined_differential_flux
  DATA_TYPE: CDF_REAL4
  CATDESC: Combined differential flux
  DEPEND_0: epoch
  DEPEND_1: combined_energy
  VAR_TYPE: data
  RECORD_VARYING: RV
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Combined Differential Flux
  FORMAT: F19.3
  LABLAXIS: Combined differential flux
  UNITS: cm!E-2!N s!E-1!N sr!E-1!N (eV/q)!E-1!N
  VALIDMIN: 0
  VALIDMAX: 1.00e+11
  FILLVAL: -1.000000e+31
  LABL_PTR_1: combined_energy_label
  SCALETYP: log
  DELTA_PLUS_VAR: combined_differential_flux_stat_uncert
  DELTA_MINUS_VAR: combined_differential_flux_stat_uncert
  SCALEMIN: 10
  SCALEMAX: 1.50e+8
combined_differential_flux_stat_uncert:
  NAME: combined_differential_flux_stat_uncert
  DATA_TYPE: CDF_REAL4
  CATDESC: Combined differential flux uncertainty
  DEPEND_0: epoch
  DEPEND_1: combined_energy
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Combined Differential Flux Uncertainty
  FORMAT: F19.3
  LABLAXIS: Combined differential flux uncertainty
  UNITS: cm!E-2!N s!E-1!N sr!E-1!N (eV/q)!E-1!N
  VALIDMIN: 0
  VALIDMAX: 1.00e+8
  FILLVAL: -1.000000e+31
  LABL_PTR_1: combined_energy_label
combined_energy_label:
  NAME: combined_energy_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label for combined energy
  VAR_TYPE: metadata
  FIELDNAM: Label For Combined Energy
  FORMAT: a20
  FILLVAL: ' '