imap_hit_l3_macropixel:
  Data_level: "3"
  Instrument_type: Particles (space)
  Data_type: L3_Macropixel>Level-3 Science data
  Logical_source_description: HIT Instrument Level-3 Macropixel Intensity Science Data
