epoch:
   NAME: epoch
   DATA_TYPE: CDF_TIME_TT2000
   CATDESC: epoch
   VAR_TYPE: support_data
   RECORD_VARYING: rv
   FIELDNAM: Epoch
   FORMAT: ' '
   LABLAXIS: Epoch
   UNITS: ns
   VALIDMIN: 2010-01-01T00:00:00.000000000
   VALIDMAX: 2059-12-31T23:59:58.999000000
   FILLVAL: 9999-12-31T23:59:59.999999999
   TIME_BASE: J2000
   TIME_SCALE: TT
   DELTA_PLUS_VAR: epoch_delta
   DELTA_MINUS_VAR: epoch_delta
   MONOTON: INCREASE
   REFERENCE_POSITION: Rotating Earth Geoid
   SI_CONVERSION: 1e-9>seconds
epoch_delta:
   NAME: epoch_delta
   DATA_TYPE: CDF_INT8
   CATDESC: epoch_delta
   DEPEND_0: epoch
   VAR_TYPE: support_data
   RECORD_VARYING: rv
   FIELDNAM: Epoch delta
   FORMAT: I19
   LABLAXIS: Epoch delta
   UNITS: ns
   VALIDMIN: 0
   VALIDMAX: 31536000000000000
   FILLVAL: -9223372036854775808
energy:
   NAME: energy
   DATA_TYPE: CDF_REAL4
   CATDESC: energy
   VAR_TYPE: support_data
   RECORD_VARYING: nrv
   FIELDNAM: Energy
   FORMAT: F6.2
   LABLAXIS: Energy
   UNITS: keV
   VALIDMIN: 0.0
   VALIDMAX: 100.0
   FILLVAL: -1.00E+31
   DELTA_PLUS_VAR: energy_delta_plus
   DELTA_MINUS_VAR: energy_delta_minus
energy_delta_plus:
   NAME: energy_delta_plus
   DATA_TYPE: CDF_REAL4
   CATDESC: energy_delta_plus
   VAR_TYPE: support_data
   RECORD_VARYING: nrv
   FIELDNAM: Energy delta plus
   FORMAT: F6.2
   LABLAXIS: Energy delta plus
   UNITS: keV
   VALIDMIN: 0.0
   VALIDMAX: 100.0
   FILLVAL: -1.00E+31
energy_delta_minus:
   NAME: energy_delta_minus
   DATA_TYPE: CDF_REAL4
   CATDESC: energy_delta_minus
   VAR_TYPE: support_data
   RECORD_VARYING: nrv
   FIELDNAM: Energy delta minus
   FORMAT: F6.2
   LABLAXIS: Energy delta minus
   UNITS: keV
   VALIDMIN: 0.0
   VALIDMAX: 100.0
   FILLVAL: -1.00E+31
latitude:
   NAME: latitude
   DATA_TYPE: CDF_REAL4
   CATDESC: latitude
   VAR_TYPE: support_data
   RECORD_VARYING: nrv
   FIELDNAM: Latitude
   FORMAT: F6.1
   LABLAXIS: Latitude
   UNITS: Degrees
   VALIDMIN: -90.0
   VALIDMAX: 90.0
   FILLVAL: -1.00E+31
longitude:
   NAME: longitude
   DATA_TYPE: CDF_REAL4
   CATDESC: longitude
   VAR_TYPE: support_data
   RECORD_VARYING: nrv
   FIELDNAM: Longitude
   FORMAT: F6.1
   LABLAXIS: Longitude
   UNITS: Degrees
   VALIDMIN: 0.0
   VALIDMAX: 360.0
   FILLVAL: -1.00E+31
ena_intensity:
   NAME: ena_intensity
   DATA_TYPE: CDF_REAL4
   CATDESC: ena_intensity
   DEPEND_0: epoch
   DEPEND_1: energy
   DEPEND_2: longitude
   DEPEND_3: latitude
   VAR_TYPE: data
   RECORD_VARYING: rv
   DISPLAY_TYPE: image
   VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
   FIELDNAM: Intensity
   FORMAT: F12.1
   LABLAXIS: Intensity
   UNITS: cm -2 s -1 sr -1 keV -1
   VALIDMIN: 0.0
   VALIDMAX: 1.00E+9
   FILLVAL: -1.00E+31
   LABL_PTR_1: energy_label
   LABL_PTR_2: lon_label
   LABL_PTR_3: lat_label
ena_intensity_random_unc:
   NAME: ena_intensity_random_unc
   DATA_TYPE: CDF_REAL4
   CATDESC: ena_intensity_random_unc
   DEPEND_0: epoch
   DEPEND_1: energy
   DEPEND_2: longitude
   DEPEND_3: latitude
   VAR_TYPE: support_data
   RECORD_VARYING: rv
   FIELDNAM: Intensity Random Uncertainty
   FORMAT: F12.1
   LABLAXIS: σ
   UNITS: cm -2 s -1 sr -1 keV -1
   VALIDMIN: 0.0
   VALIDMAX: 1.00E+9
   FILLVAL: -1.00E+31
   LABL_PTR_1: energy_label
   LABL_PTR_2: lon_label
   LABL_PTR_3: lat_label
ena_intensity_systematic_unc:
   NAME: ena_intensity_systematic_unc
   DATA_TYPE: CDF_REAL4
   CATDESC: ena_intensity_systematic_unc
   DEPEND_0: epoch
   DEPEND_1: energy
   DEPEND_2: longitude
   DEPEND_3: latitude
   VAR_TYPE: support_data
   RECORD_VARYING: rv
   FIELDNAM: Intensity Systematic Uncertainty
   FORMAT: F12.1
   LABLAXIS: σ NS
   UNITS: cm -2 s -1 sr -1 keV -1
   VALIDMIN: 0.0
   VALIDMAX: 1.00E+9
   FILLVAL: -1.00E+31
   LABL_PTR_1: energy_label
   LABL_PTR_2: lon_label
   LABL_PTR_3: lat_label
exposure_factor:
   NAME: exposure_factor
   DATA_TYPE: CDF_REAL4
   CATDESC: exposure_factor
   DEPEND_0: epoch
   DEPEND_1: energy
   DEPEND_2: longitude
   DEPEND_3: latitude
   VAR_TYPE: data
   RECORD_VARYING: rv
   DISPLAY_TYPE: no_plot
   FIELDNAM: Exposure
   FORMAT: F12.1
   LABLAXIS: Exposure
   UNITS: s
   VALIDMIN: 0.0
   VALIDMAX: 1.00E+9
   FILLVAL: -1.00E+31
   LABL_PTR_1: energy_label
   LABL_PTR_2: lon_label
   LABL_PTR_3: lat_label
obs_date:
   NAME: obs_date
   DATA_TYPE: CDF_TIME_TT2000
   CATDESC: obs_date
   DEPEND_0: epoch
   DEPEND_1: energy
   DEPEND_2: longitude
   DEPEND_3: latitude
   VAR_TYPE: data
   RECORD_VARYING: rv
   DISPLAY_TYPE: image
   FIELDNAM: Observation Date
   FORMAT: ' '
   LABLAXIS: Obs Date
   UNITS: ns
   VALIDMIN: 2010-01-01T00:00:00.000000000
   VALIDMAX: 2059-12-31T23:59:58.999000000
   FILLVAL: 9999-12-31T23:59:59.999999999
   LABL_PTR_1: energy_label
   LABL_PTR_2: lon_label
   LABL_PTR_3: lat_label
obs_date_range:
   NAME: obs_date_range
   DATA_TYPE: CDF_INT8
   CATDESC: obs_date_range
   DEPEND_0: epoch
   DEPEND_1: energy
   DEPEND_2: longitude
   DEPEND_3: latitude
   VAR_TYPE: data
   RECORD_VARYING: rv
   DISPLAY_TYPE: image
   FIELDNAM: Observation Date Range
   FORMAT: I19
   LABLAXIS: Observation Date Range
   UNITS: ns
   VALIDMIN: 0
   VALIDMAX: 31536000000000000
   FILLVAL: -9223372036854775808
   LABL_PTR_1: energy_label
   LABL_PTR_2: lon_label
   LABL_PTR_3: lat_label
solid_angle:
   NAME: solid_angle
   DATA_TYPE: CDF_REAL4
   CATDESC: solid_angle
   DEPEND_0: epoch
   DEPEND_1: energy
   DEPEND_2: longitude
   DEPEND_3: latitude
   VAR_TYPE: data
   RECORD_VARYING: rv
   DISPLAY_TYPE: image
   FIELDNAM: Solid Angle
   FORMAT: F6.2
   LABLAXIS: Solid Angle
   UNITS: sr
   VALIDMIN: 0.0
   VALIDMAX: 12.56637061
   FILLVAL: -1.00E+31
   LABL_PTR_1: energy_label
   LABL_PTR_2: lon_label
   LABL_PTR_3: lat_label
lon_label:
   NAME: lon_label
   DATA_TYPE: CDF_CHAR
   CATDESC: lon_label
   VAR_TYPE: metadata
   FIELDNAM: Longitude label
   FORMAT: A6
lat_label:
   NAME: lat_label
   DATA_TYPE: CDF_CHAR
   CATDESC: lat_label
   VAR_TYPE: metadata
   FIELDNAM: Latitude label
   FORMAT: A6
energy_label:
   NAME: energy_label
   DATA_TYPE: CDF_CHAR
   CATDESC: energy_label
   VAR_TYPE: metadata
   FIELDNAM: Energy label
   FORMAT: A8