data_variable: &data_variable
  VAR_TYPE: data
  DEPEND_0: epoch
  RECORD_VARYING: RV
  DISPLAY_TYPE: time_series

primary_data_variable: &primary_data_variable
  <<: *data_variable
  VARIABLE_PURPOSE: primary var, summary

support_data: &support_data
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  RECORD_VARYING: NRV

float_data: &float_data
  DATA_TYPE: CDF_FLOAT
  FORMAT: F15.3
  VALIDMIN: 0
  VALIDMAX: 10000000000
  FILLVAL: -1.000000E+31

per_priority: &per_priority
  <<: *primary_data_variable
  DEPEND_1: priority_index
  SCALETYP: linear
  LABL_PTR_1: priority_index_label
  DISPLAY_TYPE: spectrogram

per_event: &per_event
  <<: *per_priority
  DEPEND_2: event_index
  LABL_PTR_2: event_index_label

epoch:
  NAME: epoch
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  DATA_TYPE: CDF_TIME_TT2000
  FIELDNAM: Epoch
  RECORD_VARYING: RV
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds

epoch_delta:
  NAME: epoch_delta
  CATDESC: Epoch delta
  FIELDNAM: Epoch Delta
  DATA_TYPE: CDF_INT8
  FORMAT: I15
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 999999999999999
  FILLVAL: -9223372036854775808
  SCALETYP: linear
  LABLAXIS: Epoch delta
  DEPEND_0: epoch
  RECORD_VARYING: RV
  VAR_TYPE: support_data

event_index:
  <<: *support_data
  NAME: event_index
  CATDESC: Index of event
  FIELDNAM: Event Index
  LABLAXIS: Event
  DATA_TYPE: CDF_UINT2
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: 65535
  SCALETYP: linear
  UNITS: " "
  FORMAT: I5

priority_index:
  <<: *support_data
  NAME: priority_index
  CATDESC: Priority number where particle is observed
  FIELDNAM: Priority index
  LABLAXIS: Priority num.
  DATA_TYPE: CDF_UINT1
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 7
  FILLVAL: 255
  SCALETYP: linear
  FORMAT: I3

spin_angle_bin:
  <<: *support_data
  <<: *float_data
  NAME: spin_angle_bin
  CATDESC: Spin angle bins
  FIELDNAM: Spin angle
  LABLAXIS: Spin Angle
  UNITS: degrees
  VALIDMIN: 0
  VALIDMAX: 360
  SCALETYP: linear
  DELTA_PLUS_VAR: spin_angle_bin_delta
  DELTA_MINUS_VAR: spin_angle_bin_delta

spin_angle_bin_delta:
  <<: *support_data
  <<: *float_data
  NAME: spin_angle_bin_delta
  CATDESC: Spin angle bin deltas
  FIELDNAM: Spin angle delta
  LABLAXIS: Spin Angle delta
  UNITS: degrees
  SCALETYP: linear

energy_bin:
  <<: *support_data
  <<: *float_data
  NAME: energy_bin
  CATDESC: Energy bins
  FIELDNAM: Energy
  LABLAXIS: Energy
  UNITS: keV/e
  SCALETYP: log
  DELTA_PLUS_VAR: energy_bin_delta_plus
  DELTA_MINUS_VAR: energy_bin_delta_minus

energy_bin_delta_plus:
  <<: *support_data
  <<: *float_data
  NAME: energy_bin_delta_plus
  CATDESC: Energy bins delta plus
  FIELDNAM: Energy delta plus
  LABLAXIS: Energy delta plus
  UNITS: keV/e
  SCALETYP: log

energy_bin_delta_minus:
  <<: *support_data
  <<: *float_data
  NAME: energy_bin_delta_minus
  CATDESC: Energy bins delta minus
  FIELDNAM: Energy delta minus
  LABLAXIS: Energy delta minus
  UNITS: keV/e
  SCALETYP: log

energy_per_charge:
  <<: *per_event
  <<: *float_data
  NAME: energy_per_charge
  CATDESC: Energy per Charge
  FIELDNAM: Energy per Charge
  FORMAT: F12.4
  LABLAXIS: Energy per Charge
  SCALETYP: linear
  UNITS: keV/q
  VALIDMAX: 200.0
  VALIDMIN: 0.0


normalization:
  <<: *per_priority
  <<: *float_data
  NAME: normalization
  DEPEND_2: energy_bin
  DEPEND_3: spin_angle_bin
  VAR_TYPE: data
  CATDESC: Normalization factor
  FIELDNAM: Normalization factor
  LABLAXIS: Normalization
  UNITS: " "
  SCALETYP: linear
  VALIDMIN: 0
  VALIDMAX: 1000
  SCALEMIN: 0
  SCALEMAX: 10
  LABL_PTR_2: energy_bin_label
  LABL_PTR_3: spin_angle_bin_label
  VARIABLE_PURPOSE: ""
  DISPLAY_TYPE: spectrogram

normalization_per_event:
  <<: *per_event
  <<: *float_data
  NAME: normalization_per_event
  VAR_TYPE: data
  CATDESC: Normalization per event
  FIELDNAM: Normalization factor
  LABLAXIS: Normalization
  UNITS: " "
  SCALETYP: linear
  VALIDMIN: 0
  VALIDMAX: 1000
  SCALEMIN: 0
  SCALEMAX: 10
  VARIABLE_PURPOSE: ""
  DATA_TYPE: CDF_FLOAT
  DISPLAY_TYPE: spectrogram

mass_per_charge:
  <<: *per_event
  <<: *float_data
  NAME: mass_per_charge
  VAR_TYPE: data
  CATDESC: Mass per charge of event
  FIELDNAM: Mass per charge
  LABLAXIS: m/q
  UNITS: amu/q

mass:
  <<: *per_event
  <<: *float_data
  NAME: mass
  VAR_TYPE: data
  CATDESC: Mass of event
  FIELDNAM: Mass
  LABLAXIS: m
  UNITS: amu

apd_energy:
  <<: *per_event
  <<: *float_data
  NAME: apd_energy
  VAR_TYPE: data
  CATDESC: Deposited energy at APD
  FIELDNAM: APD Energy
  LABLAXIS: APD Energy
  UNITS: keV

energy_step:
  <<: *per_event
  CATDESC: Energy Step Index
  FIELDNAM: Energy Step
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: Energy Step
  SCALETYP: linear
  UNITS: " "
  VALIDMAX: 127
  VALIDMIN: 0
  VAR_TYPE: data
  DATA_TYPE: CDF_UINT1

gain:
  <<: *per_event
  NAME: gain
  VAR_TYPE: data
  CATDESC: Gain
  FIELDNAM: Gain
  LABLAXIS: Gain
  DATA_TYPE: CDF_UINT1
  FORMAT: I3
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: 255

apd_id:
  <<: *per_event
  NAME: apd_id
  VAR_TYPE: data
  CATDESC: APD ID
  FIELDNAM: APD ID
  LABLAXIS: APD ID
  DATA_TYPE: CDF_UINT1
  FORMAT: I3
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 31
  FILLVAL: 255

multi_flag:
  <<: *per_event
  NAME: multi_flag
  VAR_TYPE: data
  CATDESC: Multi flag
  FIELDNAM: Multi flag
  LABLAXIS: Multi flag
  DATA_TYPE: CDF_UINT1
  FORMAT: I3
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: 255

num_events:
  <<: *per_priority
  NAME: num_events
  VAR_TYPE: data
  CATDESC: Number of events
  FIELDNAM: Number of events
  LABLAXIS: Num. events
  DATA_TYPE: CDF_UINT2
  FORMAT: I5
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 10000
  FILLVAL: 65535

data_quality:
  <<: *per_priority
  NAME: data_quality
  VAR_TYPE: metadata
  CATDESC: Data quality
  FIELDNAM: Data quality
  LABLAXIS: Data quality
  DATA_TYPE: CDF_UINT1
  FORMAT: I3
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: 255

tof:
  <<: *per_event
  <<: *float_data
  NAME: tof
  VAR_TYPE: data
  CATDESC: Time of flight
  FIELDNAM: Time of flight
  LABLAXIS: TOF
  UNITS: ns
  SCALEMIN: 1
  SCALEMAX: 1.0e+3

priority_index_label:
  NAME: priority_index_label
  CATDESC: Label for priority index
  FIELDNAM: Priority index label
  DATA_TYPE: CDF_CHAR
  FORMAT: a20
  VAR_TYPE: metadata
  FILLVAL: ' '

event_index_label:
  NAME: event_index_label
  CATDESC: Label for event index
  FIELDNAM: Event index label
  DATA_TYPE: CDF_CHAR
  FORMAT: a20
  VAR_TYPE: metadata
  FILLVAL: ' '

energy_bin_label:
  NAME: energy_bin_label
  CATDESC: Label for energy bin
  FIELDNAM: Energy bin label
  DATA_TYPE: CDF_CHAR
  FORMAT: a20
  VAR_TYPE: metadata
  FILLVAL: ' '

spin_angle_bin_label:
  NAME: spin_angle_bin_label
  CATDESC: Label for spin angle bin
  FIELDNAM: Spin angle bin label
  DATA_TYPE: CDF_CHAR
  FORMAT: a20
  VAR_TYPE: metadata
  FILLVAL: ' '

spin_angle:
  <<: *per_event
  <<: *float_data
  NAME: spin_angle
  VAR_TYPE: support_data
  CATDESC: Spin angle per event
  FIELDNAM: Spin angle
  LABLAXIS: Spin angle
  UNITS: degrees
  VALIDMAX: 360
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 360

spin_sector:
  <<: *per_event
  NAME: spin_sector
  VAR_TYPE: support_data
  CATDESC: Spin sector per event
  FIELDNAM: Spin sector
  LABLAXIS: Spin sector
  DICT_KEY: SPASE>Support>SupportQuantity:Positional
  UNITS: ' '
  SCALETYP: linear
  DATA_TYPE: CDF_UINT1
  FORMAT: I2
  VALIDMIN: 0
  VALIDMAX: 23
  FILLVAL: 255

elevation:
  <<: *per_event
  <<: *float_data
  NAME: elevation
  VAR_TYPE: support_data
  CATDESC: Elevation per event
  FIELDNAM: Elevation
  LABLAXIS: Elevation
  UNITS: degrees
  VALIDMAX: 360
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 360

position:
  <<: *per_event
  NAME: position
  VAR_TYPE: support_data
  CATDESC: Position index per event
  FIELDNAM: Position index
  LABLAXIS: Position index
  DATA_TYPE: CDF_UINT1
  UNITS: " "
  VALIDMIN: 1
  VALIDMAX: 31
  FILLVAL: 255
  SCALETYP: linear
  FORMAT: I3

half_spin_per_esa_step:
  NAME: half_spin_per_esa_step
  CATDESC: Half spin number for each step of energy
  DEPEND_0: epoch
  DEPEND_1: esa_step
  FIELDNAM: Half Spin Number
  DATA_TYPE: CDF_UINT1
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: Half Spin Number
  SCALETYP: linear
  UNITS: half spin number
  VALIDMIN: 0
  VALIDMAX: 63
  VAR_TYPE: support_data
  VARIABLE_PURPOSE: ""
  RECORD_VARYING: RV

rgfo_spin_sector:
  NAME: rgfo_spin_sector
  CATDESC: Spin Sector When Reduced Gain Factor Operation (RGFO) was activated
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: RGFO Spin Sector
  DATA_TYPE: CDF_UINT1
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: RGFO Spin Sector
  SCALETYP: linear
  UNITS:  spin sector
  VALIDMIN: 0
  VALIDMAX: 255
  VAR_NOTES: Indicates the spin sector when Reduced Gain Factor Operation (RGFO) was activated. In RGFO, the Entrance ESA voltage is reduced in order to limit the number of ions that reach the detectors.
  VAR_TYPE: data
  VARIABLE_PURPOSE: ""
  RECORD_VARYING: RV

rgfo_esa_step:
  NAME: rgfo_esa_step
  CATDESC: Energy Step When Reduced Gain Factor Operation (RGFO) was activated
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: RGFO Energy Step
  DATA_TYPE: CDF_UINT1
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: RGFO Energy Step
  SCALETYP: linear
  UNITS: energy step
  VALIDMIN: 0
  VALIDMAX: 255
  VAR_NOTES: Indicates the energy step when Reduced Gain Factor Operation (RGFO) was activated. In RGFO, the Entrance ESA voltage is reduced in order to limit the number of ions that reach the detectors.
  VAR_TYPE: data
  VARIABLE_PURPOSE: ""
  RECORD_VARYING: RV

nso_spin_sector:
  NAME: nso_spin_sector
  CATDESC: Spin Sector When No Scan Operation (NSO) was activated
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: NSO Spin Sector
  DATA_TYPE: CDF_UINT1
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: NSO Spin Sector
  SCALETYP: linear
  UNITS: spin sector
  VALIDMIN: 0
  VALIDMAX: 255
  VAR_NOTES: Indicates the spin sector when No Scan Operation (NSO) was activated. In NSO, the ESA voltage is set to the first step in the scan and remains fixed until the next cycle boundary.
  VAR_TYPE: data
  VARIABLE_PURPOSE: ""
  RECORD_VARYING: RV

nso_esa_step:
  NAME: nso_esa_step
  CATDESC: Energy Step When No Scan Operation (NSO) was activated
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: NSO Energy Step
  DATA_TYPE: CDF_UINT1
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: NSO Energy Step
  SCALETYP: linear
  UNITS: energy step
  VALIDMIN: 0
  VALIDMAX: 255
  VAR_NOTES: Indicates the energy step when No Scan Operation (NSO) was activated. In NSO, the ESA voltage is set to the first step in the scan and remains fixed until the next cycle boundary.
  VAR_TYPE: data
  VARIABLE_PURPOSE: ""
  RECORD_VARYING: RV

esa_step:
  NAME: esa_step
  DATA_TYPE: CDF_UINT1
  CATDESC: Energy per charge (E/q) sweeping step
  FIELDNAM: Energy Index
  FILLVAL: 255
  FORMAT: I3
  LABLAXIS: Energy Index
  SCALETYP: linear
  UNITS: " "
  VALIDMIN: 0
  VALIDMAX: 127
  VAR_TYPE: support_data
  RECORD_VARYING: NRV

type:
  <<: *per_event
  NAME: type
  CATDESC: Event Type
  FIELDNAM: Type
  LABLAXIS: Type
  SCALETYP: linear
  UNITS: " "
  DATA_TYPE: CDF_UINT1
  VALIDMAX: 4
  VALIDMIN: 0
  FORMAT: I1
  FILLVAL: 255
