epoch:
  NAME: epoch
  DATA_TYPE: CDF_TIME_TT2000
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  RECORD_VARYING: RV
  FIELDNAM: Epoch
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 1990-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  TIME_BASE: J2000
  TIME_SCALE: TT
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SCALETYP: linear
  SI_CONVERSION: 1e-9>seconds
energy_grid:
  NAME: energy_grid
  DATA_TYPE: CDF_FLOAT
  CATDESC: Energies associated with the survival probabilities for IMAP-Lo
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Energy
  FORMAT: g9.3
  LABLAXIS: energy
  UNITS: kEV
  VALIDMIN: 0
  VALIDMAX: 10000000000
  FILLVAL: -1.0000E+31
spin_angle:
  NAME: spin_angle
  DATA_TYPE: CDF_FLOAT
  CATDESC: Angle on the circle around axis rotation, with the radius elongation angle. The 0 spin_angle is the direction nearest north pole.
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  FIELDNAM: Spin Angle
  FORMAT: g9.3
  LABLAXIS: spin angle
  UNITS: degrees
  VALIDMIN: 0
  VALIDMAX: 360
  FILLVAL: -1.0000E+31
surv_prob:
  NAME: surv_prob
  DATA_TYPE: CDF_FLOAT
  CATDESC: Survival probabilities for IMAP-Lo
  VAR_TYPE: data
  RECORD_VARYING: RV
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: spin_angle
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  FIELDNAM: Probability Of Survival
  FORMAT: g9.3
  LABLAXIS: probability of survival
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -1.0000E+31
  LABL_PTR_1: energy_label
  LABL_PTR_2: spin_angle_label
spin_axis_latitude:
  NAME: spin_axis_latitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: Latitude of spin axis
  VAR_TYPE: metadata
  RECORD_VARYING: RV
  FIELDNAM: Spin Axis Latitude
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
spin_axis_longitude:
  NAME: spin_axis_longitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: Longitude of spin axis
  VAR_TYPE: metadata
  RECORD_VARYING: RV
  FIELDNAM: Spin Axis Longitude
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
energy_label:
  NAME: energy_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label for energy
  VAR_TYPE: metadata
  FIELDNAM: Energy Label
  FORMAT: a20
  FILLVAL: ' '
spin_angle_label:
  NAME: spin_angle_label
  DATA_TYPE: CDF_CHAR
  CATDESC: Label for spin angle
  VAR_TYPE: metadata
  FIELDNAM: Spin Angle Label
  FORMAT: a20
  FILLVAL: ' '
elongation:
  NAME: elongation
  DATA_TYPE: CDF_UINT2
  CATDESC: Position of Lo instrument
  VAR_TYPE: support_data
  FIELDNAM: Elongation
  LABLAXIS: Elongation
  DEPEND_0: epoch
  FORMAT: I3
  UNITS: degree
  FILLVAL: 65535
  VALIDMAX: 105
  VALIDMIN: 75
  RECORD_VARYING: RV
program_version:
  NAME: program_version
  DATA_TYPE: CDF_CHAR
  CATDESC: Program version
  VAR_TYPE: metadata
  FIELDNAM: Program Version
  FORMAT: a20
  FILLVAL: ' '
spacecraft_radius:
  NAME: spacecraft_radius
  DATA_TYPE: CDF_FLOAT
  CATDESC: Distance from IMAP to sun
  VAR_TYPE: metadata
  FIELDNAM: Spacecraft Radius
  RECORD_VARYING: RV
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
  UNITS: AU
spacecraft_latitude:
  NAME: spacecraft_latitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft latitude
  VAR_TYPE: metadata
  FIELDNAM: Spacecraft Latitude
  RECORD_VARYING: RV
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: -90
  VALIDMAX: 90
spacecraft_longitude:
  NAME: spacecraft_longitude
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft longitude
  VAR_TYPE: metadata
  FIELDNAM: Spacecraft Longitude
  RECORD_VARYING: RV
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
  UNITS: degrees
  VALIDMIN: 0
  VALIDMAX: 360
spacecraft_velocity_x:
  NAME: spacecraft_velocity_x
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft x velocity
  VAR_TYPE: metadata
  FIELDNAM: Spacecraft Velocity X
  RECORD_VARYING: RV
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
  UNITS: km/s
  VALIDMIN: -50
  VALIDMAX: 50
spacecraft_velocity_y:
  NAME: spacecraft_velocity_y
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft y velocity
  VAR_TYPE: metadata
  FIELDNAM: Spacecraft Velocity Y
  RECORD_VARYING: RV
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
  UNITS: km/s
  VALIDMIN: -50
  VALIDMAX: 50
spacecraft_velocity_z:
  NAME: spacecraft_velocity_z
  DATA_TYPE: CDF_FLOAT
  CATDESC: IMAP spacecraft z velocity
  VAR_TYPE: metadata
  FIELDNAM: Spacecraft Velocity Z
  RECORD_VARYING: RV
  FORMAT: F9.3
  FILLVAL: -1.0000E+31
  UNITS: km/s
  VALIDMIN: -50
  VALIDMAX: 50