imap_glows_l3e_survival-probability-lo:
  Data_level: "3e"
  Data_type: L3E_survival-probability-lo>Level-3E Survival Probability Lo
  Logical_source_description: IMAP Mission GLOWS Lo
imap_glows_l3e_survival-probability-hi-45:
  Data_level: "3e"
  Data_type: L3E_survival-probability-hi-45>Level-3E Survival Probability Hi 45
  Logical_source_description: IMAP Mission GLOWS Hi 45
imap_glows_l3e_survival-probability-hi-90:
  Data_level: "3e"
  Data_type: L3E_survival-probability-hi-90>Level-3E Survival Probability Hi 90
  Logical_source_description: IMAP Mission GLOWS Hi 90
imap_glows_l3e_survival-probability-ul:
  Data_level: "3e"
  Data_type: L3E_survival-probability-ul>Level-3E Survival Probability Ul
  Logical_source_description: IMAP Mission GLOWS Ultra