default_attrs: &default_timeseries
  FORMAT: F19.3
  DEPEND_0: epoch
  FILLVAL: -1.000000e+31
  VALIDMIN: 0
  VALIDMAX: 9223372036854775807
  UNITS: ' '

proton_sw_velocity:
  <<: *default_timeseries
  CATDESC: Proton Solar Wind Velocity
  FIELDNAM: proton_sw_velocity
  DELTA_MINUS_VAR: proton_sw_velocity_delta_minus
  DELTA_PLUS_VAR: proton_sw_velocity_delta_plus
  UNITS: km/s
  LABLAXIS: Velocity
  SCALETYP: linear
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

proton_sw_velocity_delta_minus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Velocity Delta Minus
  FIELDNAM: proton_sw_velocity_delta_minus
  UNITS: km/s
  LABLAXIS: Velocity Delta Minus

proton_sw_velocity_delta_plus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Velocity Delta Plus
  FIELDNAM: proton_sw_velocity_delta_plus
  UNITS: km/s
  LABLAXIS: Velocity Delta Plus

proton_sw_vdf:
  <<: *default_timeseries
  DEPEND_1: proton_sw_velocity
  CATDESC: Proton Solar Wind Combined VDF
  FIELDNAM: proton_sw_vdf
  DELTA_MINUS_VAR: proton_sw_vdf_delta
  DELTA_PLUS_VAR: proton_sw_vdf_delta
  LABLAXIS: F(v)
  SCALETYP: log
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  SCALEMIN: .000001
  SCALEMAX: 1000000
  UNITS: (gm/q)/(cm^2 s sr eV/q)

proton_sw_vdf_delta:
  <<: *default_timeseries
  DEPEND_1: proton_sw_velocity
  VAR_TYPE: support_data
  CATDESC: Proton Solar Wind Combined VDF Uncertainty
  FIELDNAM: proton_sw_vdf_delta
  UNITS: (gm/q)/(cm^2 s sr eV/q)
  LABLAXIS: F(v) Delta

alpha_sw_velocity:
  <<: *default_timeseries
  CATDESC: Alpha Solar Wind Velocity
  FIELDNAM: alpha_sw_velocity
  DELTA_MINUS_VAR: alpha_sw_velocity_delta_minus
  DELTA_PLUS_VAR: alpha_sw_velocity_delta_plus
  UNITS: km/s
  LABLAXIS: Velocity
  SCALETYP: linear
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

alpha_sw_velocity_delta_minus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Alpha Solar Wind Velocity Delta Minus
  FIELDNAM: alpha_sw_velocity_delta_minus
  UNITS: km/s
  LABLAXIS: Velocity Minus

alpha_sw_velocity_delta_plus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Alpha Solar Wind Velocity Delta Plus
  FIELDNAM: alpha_sw_velocity_delta_plus
  UNITS: km/s
  LABLAXIS: Velocity Delta Plus

alpha_sw_vdf:
  <<: *default_timeseries
  DEPEND_1: alpha_sw_velocity
  CATDESC: Alpha Solar Wind Combined VDF
  FIELDNAM: alpha_sw_vdf
  DELTA_MINUS_VAR: alpha_sw_vdf_delta
  DELTA_PLUS_VAR: alpha_sw_vdf_delta
  LABLAXIS: F(v)
  SCALETYP: log
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  SCALEMIN: .000001
  SCALEMAX: 1000000
  UNITS: (gm/q)/(cm^2 s sr eV/q)

alpha_sw_vdf_delta:
  <<: *default_timeseries
  DEPEND_1: alpha_sw_velocity
  VAR_TYPE: support_data
  CATDESC: Alpha Solar Wind Combined VDF Uncertainty
  FIELDNAM: alpha_sw_vdf_delta
  UNITS: (gm/q)/(cm^2 s sr eV/q)
  LABLAXIS: F(v) Delta

pui_sw_velocity:
  <<: *default_timeseries
  CATDESC: Pickup Ion Solar Wind Velocity
  FIELDNAM: pui_sw_velocity
  DELTA_MINUS_VAR: pui_sw_velocity_delta_minus
  DELTA_PLUS_VAR: pui_sw_velocity_delta_plus
  UNITS: km/s
  LABLAXIS: Velocity
  SCALETYP: linear
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

pui_sw_velocity_delta_minus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Pickup Ion Solar Wind Velocity Delta Minus
  FIELDNAM: pui_sw_velocity_delta_minus
  UNITS: km/s
  LABLAXIS: Velocity Delta Minus

pui_sw_velocity_delta_plus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Pickup Ion Solar Wind Velocity Delta Plus
  FIELDNAM: pui_sw_velocity_delta_plus
  UNITS: km/s
  LABLAXIS: Velocity Delta Plus

pui_sw_vdf:
  <<: *default_timeseries
  DEPEND_1: pui_sw_velocity
  CATDESC: Pickup Ion Solar Wind Combined VDF
  FIELDNAM: pui_sw_vdf
  DELTA_MINUS_VAR: pui_sw_vdf_delta
  DELTA_PLUS_VAR: pui_sw_vdf_delta
  LABLAXIS: F(v)
  SCALETYP: log
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  SCALEMIN: .000001
  SCALEMAX: 1000000
  UNITS: (gm/q)/(cm^2 s sr eV/q)


pui_sw_vdf_delta:
  <<: *default_timeseries
  DEPEND_1: pui_sw_velocity
  VAR_TYPE: support_data
  CATDESC: Pickup Ion Solar Wind Combined VDF Uncertainty
  FIELDNAM: pui_sw_vdf_delta
  UNITS: (gm/q)/(cm^2 s sr eV/q)
  LABLAXIS: F(v) Delta

combined_energy:
  <<: *default_timeseries
  CATDESC: Solar Wind Energy
  FIELDNAM: combined_energy
  DELTA_MINUS_VAR: combined_energy_delta_minus
  DELTA_PLUS_VAR: combined_energy_delta_plus
  UNITS: eV/q
  LABLAXIS: Energy
  SCALETYP: log
  VAR_TYPE: support_data
  DISPLAY_TYPE: time_series
  SCALEMIN: 0
  SCALEMAX: 1000

combined_energy_delta_minus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Solar Wind Energy Delta Minus
  FIELDNAM: combined_energy_delta_minus
  UNITS: eV/q
  LABLAXIS: Energy Delta Minus

combined_energy_delta_plus:
  <<: *default_timeseries
  VAR_TYPE: support_data
  CATDESC: Solar Wind Energy Delta Plus
  FIELDNAM: combined_energy_delta_plus
  UNITS: eV/q
  LABLAXIS: Energy Delta Plus

combined_differential_flux:
  <<: *default_timeseries
  DEPEND_1: combined_energy
  CATDESC: Combined Differential Flux
  FIELDNAM: combined_differential_flux
  DELTA_MINUS_VAR: combined_differential_flux_delta
  DELTA_PLUS_VAR: combined_differential_flux_delta
  LABLAXIS: Differential Flux
  SCALETYP: log
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  SCALEMIN: .000001
  SCALEMAX: 1000000
  UNITS: 'cm!E-2!N sr!E-1!N s!E-1!N (eV/q)!E-1!N'


combined_differential_flux_delta:
  <<: *default_timeseries
  DEPEND_1: combined_energy
  VAR_TYPE: support_data
  CATDESC: Combined Differential Flux Uncertainty
  FIELDNAM: combined_differential_flux_delta
  UNITS: 'cm!E-2!N sr!E-1!N s!E-1!N (eV/q)!E-1!N'
  LABLAXIS: Differential Flux Uncertainty

epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  DELTA_MINUS_VAR: epoch_delta
  DELTA_PLUS_VAR: epoch_delta
  FILLVAL: 9999-12-31T23:59:59.999999999
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2040-01-01T00:00:00.000000000
  FORMAT: " "

epoch_delta:
  CATDESC: epoch_DELTA
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: epoch_delta
  FILLVAL: -9223372036854775808
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  SCALEMIN: 0
  SCALEMAX: 86000000000000
  SCALETYP: linear
  UNITS: ns
  VAR_TYPE: support_data
  FORMAT: 19I