imap_glows_l3c_sw-profile:
  Data_level: "3c"
  Data_type: L3C_sw-profile>Level-3C Solar Wind Profile
  Logical_source_description: IMAP Mission GLOWS Carrington period-averaged solar wind plasma speed and proton density profiles