epoch:
   NAME: epoch
   DATA_TYPE: CDF_TIME_TT2000
   CATDESC: Time, number of nanoseconds since J2000 with leap seconds included for center of CR
   VAR_TYPE: support_data
   RECORD_VARYING: RV
   FIELDNAM: Epoch
   FORMAT: ' '
   LABLAXIS: Epoch
   UNITS: ns
   VALIDMIN: 2010-01-01T00:00:00.000000000
   VALIDMAX: 2059-12-31T23:59:58.999000000
   FILLVAL: 9999-12-31T23:59:59.999999999
   SCALE_TYP: linear
   TIME_BASE: J2000
   TIME_SCALE: TT
   DELTA_PLUS_VAR: epoch_delta
   DELTA_MINUS_VAR: epoch_delta
   MONOTON: INCREASE
   REFERENCE_POSITION: Rotating Earth Geoid
   SI_CONVERSION: 1e-9>seconds
epoch_delta:
   NAME: epoch_delta
   DATA_TYPE: CDF_INT8
   CATDESC: Time bin of half a carrington rotation
   DEPEND_0: epoch
   VAR_TYPE: support_data
   RECORD_VARYING: RV
   FIELDNAM: Epoch delta
   FORMAT: I19
   LABLAXIS: Epoch delta
   UNITS: ns
   VALIDMIN: 0
   VALIDMAX: 2592000000000000
   FILLVAL: -9223372036854775808
   SCALE_TYP: linear
cr:
   NAME: cr
   DATA_TYPE: CDF_INT2
   CATDESC: Carrington rotation number
   DEPEND_0: epoch
   VAR_TYPE: support_data
   RECORD_VARYING: RV
   FIELDNAM: Carrington rotation
   FORMAT: I14
   LABLAXIS: Carrington rotation
   UNITS: ' '
   VALIDMIN: 2000
   VALIDMAX: 3000
   FILLVAL: -32768
   SCALE_TYP: linear
uv_anisotropy_factor:
   NAME: uv_anisotropy_factor
   DATA_TYPE: CDF_FLOAT
   CATDESC: UV anisotropy factor
   DEPEND_0: epoch
   DEPEND_1: lat_grid
   VAR_TYPE: support_data
   RECORD_VARYING: RV
   FIELDNAM: UV anisotropy factor
   FORMAT: F9.3
   LABLAXIS: UV anisotropy factor
   UNITS: ' '
   VALIDMIN: 0
   VALIDMAX: 10
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
   SCALEMIN: 0
   SCALEMAX: 10
lat_grid:
   NAME: lat_grid
   DATA_TYPE: CDF_FLOAT
   CATDESC: latitudinal grid from -90 to 90
   VAR_TYPE: support_data
   RECORD_VARYING: NRV
   FIELDNAM: Lat grid
   FORMAT: F9.3
   LABLAXIS: Lat grid
   UNITS: degrees
   VALIDMIN: -90
   VALIDMAX: 90
   FILLVAL: -1.00E+31
   LABL_PTR_1: lat_grid_label
   SCALE_TYP: linear
lat_grid_delta:
   NAME: lat_grid_delta
   DATA_TYPE: CDF_FLOAT
   CATDESC: latitudinal grid delta
   VAR_TYPE: support_data
   RECORD_VARYING: NRV
   FIELDNAM: Lat grid delta
   FORMAT: F9.3
   LABLAXIS: Lat grid delta
   UNITS: degrees
   VALIDMIN: 0
   VALIDMAX: 90
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
   DELTA_PLUS_VAR: lat_grid_delta
   DELTA_MINUS_VAR: lat_grid_delta
sum_rate:
   NAME: sum_rate
   DATA_TYPE: CDF_FLOAT
   CATDESC: averaged ionization rate profile obtained from lightcurve
   DEPEND_0: epoch
   DEPEND_1: lat_grid
   VAR_TYPE: data
   RECORD_VARYING: RV
   DISPLAY_TYPE: spectrogram
   VARIABLE_PURPOSE: primary var, summary
   FIELDNAM: Sum rate
   FORMAT: F9.3
   LABLAXIS: Sum rate
   UNITS: s^-1
   VALIDMIN: 0
   VALIDMAX: 1.0
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
   DELTA_PLUS_VAR: sum_uncert
   DELTA_MINUS_VAR: sum_uncert
   SCALEMIN: 0
   SCALEMAX: 1.0e-6
ph_rate:
   NAME: ph_rate
   DATA_TYPE: CDF_FLOAT
   CATDESC: averaged photoionization rate profile
   DEPEND_0: epoch
   DEPEND_1: lat_grid
   VAR_TYPE: data
   RECORD_VARYING: RV
   DISPLAY_TYPE: spectrogram
   VARIABLE_PURPOSE: primary var, summary
   FIELDNAM: Photoionization rate
   FORMAT: F9.3
   LABLAXIS: Photoionization rate
   UNITS: s^-1
   VALIDMIN: 0
   VALIDMAX: 1.0
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
   DELTA_PLUS_VAR: ph_uncert
   DELTA_MINUS_VAR: ph_uncert
   SCALEMIN: 0
   SCALEMAX: 1.0e-6
cx_rate:
   NAME: cx_rate
   DATA_TYPE: CDF_FLOAT
   CATDESC: averaged charge exchange rate profile (stationary atom approximation)
   DEPEND_0: epoch
   DEPEND_1: lat_grid
   VAR_TYPE: data
   RECORD_VARYING: RV
   DISPLAY_TYPE: spectrogram
   VARIABLE_PURPOSE: primary var, summary
   FIELDNAM: Charge exchange rate
   FORMAT: F9.3
   LABLAXIS: Charge exchange rate
   UNITS: s^-1
   VALIDMIN: 0
   VALIDMAX: 1.0
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
   DELTA_PLUS_VAR: cx_uncert
   DELTA_MINUS_VAR: cx_uncert
   SCALEMIN: 0
   SCALEMAX: 1.0e-6
sum_uncert:
   NAME: sum_uncert
   DATA_TYPE: CDF_FLOAT
   CATDESC: averaged ionization rate profile uncertainty
   DEPEND_0: epoch
   DEPEND_1: lat_grid
   VAR_TYPE: support_data
   RECORD_VARYING: RV
   VARIABLE_PURPOSE: primary var, summary
   FIELDNAM: Sum rate uncertainty
   FORMAT: F9.3
   LABLAXIS: Sum rate uncertainty
   UNITS: s^-1
   VALIDMIN: 0
   VALIDMAX: 1.0
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
ph_uncert:
   NAME: ph_uncert
   DATA_TYPE: CDF_FLOAT
   CATDESC: averaged photoionization rate profile uncertainty
   DEPEND_0: epoch
   DEPEND_1: lat_grid
   VAR_TYPE: support_data
   RECORD_VARYING: RV
   VARIABLE_PURPOSE: primary var, summary
   FIELDNAM: Photoionization rate uncertainty
   FORMAT: F9.3
   LABLAXIS: Photoionization rate uncertainty
   UNITS: s^-1
   VALIDMIN: 0
   VALIDMAX: 1.0
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
cx_uncert:
   NAME: cx_uncert
   DATA_TYPE: CDF_FLOAT
   CATDESC: averaged charge exchange rate profile uncertainty
   DEPEND_0: epoch
   DEPEND_1: lat_grid
   VAR_TYPE: support_data
   RECORD_VARYING: RV
   VARIABLE_PURPOSE: primary var, summary
   FIELDNAM: Charge exchange rate uncertainty
   FORMAT: F9.3
   LABLAXIS: Charge exchange rate uncertainty
   UNITS: s^-1
   VALIDMIN: 0
   VALIDMAX: 1.0
   FILLVAL: -1.00E+31
   SCALE_TYP: linear
lat_grid_label:
   NAME: lat_grid_label
   DATA_TYPE: CDF_CHAR
   CATDESC: Label for lat grid
   VAR_TYPE: metadata
   FIELDNAM: lat grid label
   FORMAT: a20