imap_codice_l3a_lo-partial-densities:
  Data_level: "3a"
  Data_type: L3A_lo-partial-densities>Level-3A partial densities
  Logical_source_description: IMAP Mission CoDICE Instrument Partial Densities

imap_codice_l3a_lo-sw-ratios:
  Data_level: "3a"
  Data_type: L3A_lo-sw-ratios>Level-3A sw ratios
  Logical_source_description: IMAP Mission CoDICE Instrument SW Ratios

imap_codice_l3a_lo-direct-events:
  Data_level: "3a"
  Data_type: L3A_lo-direct-events>Level-3A direct events
  Logical_source_description: IMAP Mission CoDICE Instrument Direct Events

imap_codice_l3a_lo-sw-abundances:
  Data_level: "3a"
  Data_type: L3A_lo-sw-abundances>Level-3A charge state abundances
  Logical_source_description: IMAP Mission CoDICE Instrument Charge State Relative Abundances