float_fillval: &float_fillval -1.000000e+31
uint4_fillval: &uint4_fillval 4294967295
max_uint16: &max_uint16 65535

data_defaults: &data_defaults
  DEPEND_0: epoch
  VAR_TYPE: data
  FORMAT: F8.3
  FILLVAL: *float_fillval

timeseries_defaults: &timeseries_defaults
  <<: *data_defaults
  DISPLAY_TYPE: time_series

spectrogram_defaults: &spectrogram_defaults
  <<: *data_defaults
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram

support_data_defaults: &support_data_defaults
  <<: *data_defaults
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot

epoch:
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  FIELDNAM: epoch
  LABLAXIS: epoch
  UNITS: ns
  VAR_TYPE: support_data
  SCALETYP: linear
  MONOTON: INCREASE
  TIME_BASE: J2000
  TIME_SCALE: Terrestrial Time
  REFERENCE_POSITION: Rotating Earth Geoid
  DELTA_MINUS_VAR: epoch_delta
  DELTA_PLUS_VAR: epoch_delta
  FILLVAL: 9999-12-31T23:59:59.999999999
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2040-01-01T00:00:00.000000000
  FORMAT: " "
  DISPLAY_TYPE: no_plot

epoch_delta:
  CATDESC: epoch_DELTA
  DEPEND_0: epoch
  DISPLAY_TYPE: time_series
  FIELDNAM: epoch_delta
  LABLAXIS: Time
  FILLVAL: -9223372036854775808
  VALIDMIN: 0
  VALIDMAX: 86000000000000
  SCALEMIN: 0
  SCALEMAX: 86000000000000
  SCALETYP: linear
  UNITS: ns
  VAR_TYPE: support_data
  FORMAT: 19I

energy:
  <<: *support_data_defaults
  CATDESC: Bin Energy
  FIELDNAM: Energy
  LABLAXIS: Energy
  VALIDMIN: 1
  VALIDMAX: 10000
  SCALEMIN: 1
  SCALEMAX: 10000
  SCALETYP: log
  UNITS: eV
  DELTA_PLUS_VAR: energy_delta_plus
  DELTA_MINUS_VAR: energy_delta_minus
energy_delta_plus:
  <<: *support_data_defaults
  CATDESC: Energy bin half-width
  FIELDNAM: Energy
  LABLAXIS: Energy
  VALIDMIN: 0
  VALIDMAX: 10000
  SCALEMIN: 0
  SCALEMAX: 10000
  SCALETYP: log
  UNITS: eV
energy_delta_minus:
  <<: *support_data_defaults
  CATDESC: Energy bin half-width
  FIELDNAM: Energy
  LABLAXIS: Energy
  VALIDMIN: 0
  VALIDMAX: 10000
  SCALEMIN: 0
  SCALEMAX: 10000
  SCALETYP: log
  UNITS: eV
pitch_angle: &pitch_angle
  <<: *support_data_defaults
  CATDESC: Pitch Angle
  FIELDNAM: Pitch Angle
  LABLAXIS: Pitch Angle
  VALIDMIN: 0
  VALIDMAX: 180
  SCALEMIN: 0
  SCALEMAX: 180
  SCALETYP: linear
  UNITS: degrees
  DELTA_PLUS_VAR: pitch_angle_delta
  DELTA_MINUS_VAR: pitch_angle_delta
pitch_angle_delta:
  <<: *pitch_angle
  CATDESC: Pitch Angle bin half-width
gyrophase: &gyrophase
  <<: *support_data_defaults
  CATDESC: Gyrophase
  FIELDNAM: Gyrophase
  LABLAXIS: Gyrophase
  VALIDMIN: 0
  VALIDMAX: 360
  SCALEMIN: 0
  SCALEMAX: 360
  SCALETYP: linear
  UNITS: degrees
  DELTA_PLUS_VAR: gyrophase_delta
  DELTA_MINUS_VAR: gyrophase_delta
gyrophase_delta:
  <<: *gyrophase
  CATDESC: Gyrophase bin half-width

intensity_uncertainty_by_pitch_angle_and_gyrophase:
  CATDESC: Uncertainty Intensity organized by pitch angle and gyrophase
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pitch_angle
  DEPEND_3: gyrophase
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: primary var, summary
  LABLAXIS: Electron Intensity Uncertainty
  FORMAT: F8.3
  UNITS: cm^-2 sr^-1 s^-1 eV^-1
  VALIDMIN: 0
  FILLVAL: *float_fillval
  SCALE_TYP: linear

intensity_uncertainty_by_pitch_angle:
  CATDESC: Uncertainty of Intensity organized by pitch angle
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pitch_angle
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  VARIABLE_PURPOSE: primary var, summary
  LABLAXIS: Electron Intensity Uncertainty
  FORMAT: F8.3
  UNITS: cm^-2 sr^-1 s^-1 eV^-1
  VALIDMIN: 0
  FILLVAL: *float_fillval
  SCALE_TYP: linear

intensity_by_pitch_angle:
  CATDESC: Intensity organized by pitch angle
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pitch_angle
  DELTA_PLUS_VAR: intensity_uncertainty_by_pitch_angle
  DELTA_MINUS_VAR: intensity_uncertainty_by_pitch_angle
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  LABLAXIS: Electron Intensity
  FORMAT: F8.3
  UNITS: cm^-2 sr^-1 s^-1 eV^-1
  VALIDMIN: 1.00E-40
  FILLVAL: -1.00E+31
  SCALEMIN: 1.0e-40
  SCALEMAX: 100000
  SCALETYP: linear
intensity_by_pitch_angle_and_gyrophase:
  CATDESC: Intensity organized by pitch angle and gyrophase
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pitch_angle
  DEPEND_3: gyrophase
  DELTA_PLUS_VAR: intensity_uncertainty_by_pitch_angle_and_gyrophase
  DELTA_MINUS_VAR: intensity_uncertainty_by_pitch_angle_and_gyrophase
  VAR_TYPE: data
  DISPLAY_TYPE: spectrogram
  LABLAXIS: Electron Intensity
  FORMAT: F8.3
  UNITS: cm^-2 sr^-1 s^-1 eV^-1
  VALIDMIN: 1.00E-40
  FILLVAL: *float_fillval
  SCALEMIN: 1.0e-40
  SCALEMAX: 100000
  SCALETYP: linear

phase_space_density_by_pitch_angle: &phase_space_density_by_pitch_angle
  CATDESC: Phase space density organized by pitch angle
  DEPEND_0: epoch
  DEPEND_1: energy
  DEPEND_2: pitch_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Electron Phase Space Density
  LABLAXIS: PSD
  FILLVAL: *float_fillval
  VALIDMIN: 1.0e-40
  VALIDMAX: 100000
  SCALEMIN: 1.0e-40
  SCALEMAX: 100000
  SCALETYP: log
  UNITS: s^3 cm^-6
  VAR_TYPE: data
  FORMAT: F8.3

phase_space_density_by_pitch_angle_and_gyrophase:
  <<: *phase_space_density_by_pitch_angle
  CATDESC: Phase space density organized by pitch angle and gyrophase
  DEPEND_3: gyrophase

energy_spectrum: &energy_spectrum
  CATDESC: 1D Electron Energy Spectrum
  DEPEND_0: epoch
  DEPEND_1: energy
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Electron Flux
  LABLAXIS: Flux
  FILLVAL: *float_fillval
  VALIDMIN: 1.0e-40
  VALIDMAX: 100000
  SCALEMIN: 1.0e-40
  SCALEMAX: 100000
  SCALETYP: log
  UNITS: cm^-2 sr^-1 s^-1 eV^-1
  VAR_TYPE: data
  FORMAT: F8.3
energy_spectrum_inbound:
  <<: *energy_spectrum
  CATDESC: 1D Electron Energy Spectrum (Inbound)
energy_spectrum_outbound:
  <<: *energy_spectrum
  CATDESC: 1D Electron Energy Spectrum (Outbound)

spacecraft_potential:
  CATDESC: IMAP Spacecraft potential
  <<: *timeseries_defaults
  FIELDNAM: Spacecraft Potential
  LABLAXIS: Potential
  UNITS: V
  VALIDMIN: 0
  VALIDMAX: 100
  SCALE_TYP: linear
  SCALEMIN: 0
  SCALEMAX: 20

core_halo_breakpoint:
  CATDESC: SW Electron Core/Halo breakpoint
  <<: *timeseries_defaults
  FIELDNAM: Core/Halo Breakpoint
  LABLAXIS: Core/Halo Break
  UNITS: eV
  VALIDMIN: 15
  VALIDMAX: 200
  SCALE_TYP: linear
  SCALEMIN: 15
  SCALEMAX: 100
  SI_CONVERSION: 1.602176634e-19>joules

core_fit_num_points:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_chisq:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_chisq:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_density_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_density_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_t_parallel_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_t_parallel_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_t_perpendicular_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_t_perpendicular_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_temperature_phi_rtn_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_temperature_phi_rtn_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_temperature_theta_rtn_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_temperature_theta_rtn_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_speed_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_speed_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


core_velocity_vector_rtn_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval


halo_velocity_vector_rtn_fit:
  CATDESC: SW Electron Core/Halo breakpoint
  FILLVAL: *float_fillval

core_density_integrated:
  CATDESC: Density halo/suprathermal electrons (high energy) integrated
  FILLVAL: *float_fillval

halo_density_integrated:
  FILLVAL: *float_fillval

total_density_integrated:
  FILLVAL: *float_fillval

core_speed_integrated:
  FILLVAL: *float_fillval

halo_speed_integrated:
  FILLVAL: *float_fillval

total_speed_integrated:
  FILLVAL: *float_fillval

core_velocity_vector_rtn_integrated:
  FILLVAL: *float_fillval

halo_velocity_vector_rtn_integrated:
  FILLVAL: *float_fillval

total_velocity_vector_rtn_integrated:
  FILLVAL: *float_fillval

core_heat_flux_magnitude_integrated:
  FILLVAL: *float_fillval

core_heat_flux_theta_integrated:
  FILLVAL: *float_fillval

core_heat_flux_phi_integrated:
  FILLVAL: *float_fillval

halo_heat_flux_magnitude_integrated:
  FILLVAL: *float_fillval

halo_heat_flux_theta_integrated:
  FILLVAL: *float_fillval

halo_heat_flux_phi_integrated:
  FILLVAL: *float_fillval

total_heat_flux_magnitude_integrated:
  FILLVAL: *float_fillval

total_heat_flux_theta_integrated:
  FILLVAL: *float_fillval

total_heat_flux_phi_integrated:
  FILLVAL: *float_fillval

core_t_parallel_integrated:
  FILLVAL: *float_fillval

core_t_perpendicular_integrated:
  FILLVAL: *float_fillval

halo_t_parallel_integrated:
  FILLVAL: *float_fillval

halo_t_perpendicular_integrated:
  FILLVAL: *float_fillval

total_t_parallel_integrated:
  FILLVAL: *float_fillval

total_t_perpendicular_integrated:
  FILLVAL: *float_fillval

core_temperature_theta_rtn_integrated:
  FILLVAL: *float_fillval

core_temperature_phi_rtn_integrated:
  FILLVAL: *float_fillval

halo_temperature_theta_rtn_integrated:
  FILLVAL: *float_fillval

halo_temperature_phi_rtn_integrated:
  FILLVAL: *float_fillval

total_temperature_theta_rtn_integrated:
  FILLVAL: *float_fillval

total_temperature_phi_rtn_integrated:
  FILLVAL: *float_fillval

core_temperature_parallel_to_mag:
  FILLVAL: *float_fillval

core_temperature_perpendicular_to_mag:
  FILLVAL: *float_fillval

halo_temperature_parallel_to_mag:
  FILLVAL: *float_fillval

halo_temperature_perpendicular_to_mag:
  FILLVAL: *float_fillval

total_temperature_parallel_to_mag:
  FILLVAL: *float_fillval

total_temperature_perpendicular_to_mag:
  FILLVAL: *float_fillval

core_temperature_tensor_integrated:
  FILLVAL: *float_fillval

halo_temperature_tensor_integrated:
  FILLVAL: *float_fillval

total_temperature_tensor_integrated:
  FILLVAL: *float_fillval

