imap_hi_l3_h90-hf-sp-hae-4deg-6mo-spectral:
  Data_level: "3"
  Data_type: L3_h90-hf-sp-hae-4deg-6mo-spectral>Level-3 Spectral Fit Index
  Logical_source: imap_hi_l3_h90-hf-sp-hae-4deg-6mo-spectral
  Logical_source_description: IMAP-Hi Instrument Level-3 Spectral Fit Index.

imap_hi_l3_h90-sf-sp-hae-4deg-6mo:
  Data_level: "3"
  Data_type: L3_h90-sf-sp-hae-4deg-6mo>Level-3 Survival Corrected Full 4 degree
  Logical_source: imap_hi_l3_h90-sf-sp-hae-4deg-6mo
  Logical_source_description: IMAP-Hi Instrument Level-3 Survival Corrected Full 4 degree