primary_data_variable: &primary_data_variable
  VAR_TYPE: data
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY
  DEPEND_0: epoch
  RECORD_VARYING: RV

support_data: &support_data
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  DEPEND_0: epoch
  RECORD_VARYING: RV

primary_support_data: &primary_support_data
  <<: *support_data
  VARIABLE_PURPOSE: PRIMARY_VAR,SUMMARY

metadata_variable: &metadata_variable
  DATA_TYPE: CDF_CHAR
  VAR_TYPE: metadata
  DISPLAY_TYPE: no_plot

epoch:
  NAME: epoch
  CATDESC: Time, number of nanoseconds since J2000 with leap seconds included
  VAR_TYPE: support_data
  DATA_TYPE: CDF_TIME_TT2000
  FIELDNAM: Epoch
  RECORD_VARYING: RV
  FORMAT: ' '
  LABLAXIS: Epoch
  UNITS: ns
  VALIDMIN: 2010-01-01T00:00:00.000000000
  VALIDMAX: 2099-12-31T00:00:00.000000000
  FILLVAL: 9999-12-31T23:59:59.999999999
  SCALETYP: linear
  TIME_BASE: J2000
  TIME_SCALE: TT
  DELTA_PLUS_VAR: epoch_delta
  DELTA_MINUS_VAR: epoch_delta
  MONOTON: INCREASE
  REFERENCE_POSITION: Rotating Earth Geoid
  SI_CONVERSION: 1e-9>seconds
epoch_delta:
  NAME: epoch_delta
  CATDESC: Epoch delta
  FIELDNAM: Epoch Delta
  DATA_TYPE: CDF_INT8
  FORMAT: I19
  UNITS: ns
  VALIDMIN: 0
  VALIDMAX: 999999999999999
  FILLVAL: -9223372036854775808
  SCALETYP: linear
  LABLAXIS: Epoch delta
  DEPEND_0: epoch
  RECORD_VARYING: RV
  VAR_TYPE: support_data
identifier:
  <<: *support_data
  NAME: identifier
  CATDESC: Spin pointing number to identify observational day
  FIELDNAM: Spin pointing number
  DATA_TYPE: CDF_INT8
  FORMAT: I5
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 99999
  FILLVAL: -9223372036854775808
  SCALETYP: linear
  LABLAXIS: Pointing no.
start_time:
  <<: *support_data
  NAME: start_time
  CATDESC: Start time (UTC) of observational day
  FIELDNAM: Observation Start Time UTC
  LABLAXIS: Start time
  DATA_TYPE: CDF_CHAR
  FORMAT: A26
  FILLVAL: ' '
  UNITS: ''
end_time:
  <<: *support_data
  NAME: end_time
  CATDESC: End time (UTC) of observational day
  FIELDNAM: Observation End Time UTC
  LABLAXIS: End time
  DATA_TYPE: CDF_CHAR
  FORMAT: A26
  FILLVAL: ' '
  UNITS: ''
photon_flux:
  <<: *primary_data_variable
  NAME: photon_flux
  CATDESC: Photon flux in scanning-circle bins averaged over observational day
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Pointing-averaged Photon Flux
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F8.2
  LABLAXIS: Flux
  UNITS: Rayleigh
  VALIDMIN: 0.0
  VALIDMAX: 30000.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: photon_flux_uncertainty
  DELTA_MINUS_VAR: photon_flux_uncertainty
  SCALEMIN: 0
  SCALEMAX: 30000
  SI_CONVERSION: 1e10>s^-1 m^-2
photon_flux_uncertainty:
  <<: *support_data
  NAME: photon_flux_uncertainty
  CATDESC: Statistical uncertainties for photon flux
  DEPEND_1: spin_angle
  DISPLAY_TYPE: time_series
  FIELDNAM: Photon Flux Uncertainties
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F8.2
  LABLAXIS: Flux uncert
  UNITS: Rayleigh
  VALIDMIN: 0.0
  VALIDMAX: 30000.0
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  SI_CONVERSION: 1e10>s^-1 m^-2
raw_histogram:
  <<: *primary_data_variable
  NAME: raw_histogram
  CATDESC: Histogram of counts for observational day
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Histogram Of Counts
  DATA_TYPE: CDF_UINT4
  FORMAT: I9
  LABLAXIS: Counts
  UNITS: '#'
  VALIDMIN: 0
  VALIDMAX: 300000000
  FILLVAL: 4294967295
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 1000000
extra_heliospheric_bckgrd:
  <<: *primary_support_data
  NAME: extra_heliospheric_bckgrd
  CATDESC: Extra-heliospheric background estimate
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Extra-heliospheric Background
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F8.2
  LABLAXIS: E-H bckgrd
  UNITS: Rayleigh
  VALIDMIN: 0.0
  VALIDMAX: 30000.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 1000
  SI_CONVERSION: 1e10>s^-1 m^-2
time_dependent_bckgrd:
  <<: *primary_support_data
  NAME: time_dependent_bckgrd
  CATDESC: Time-dependent background estimate
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Time-dependent Background
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F8.2
  LABLAXIS: T-D bckgrd
  UNITS: Rayleigh
  VALIDMIN: 0.0
  VALIDMAX: 30000.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 1000
  SI_CONVERSION: 1e10>s^-1 m^-2
number_of_bins:
  <<: *support_data
  NAME: number_of_bins
  CATDESC: Number of histogram bins
  DISPLAY_TYPE: time_series
  FIELDNAM: Number Of Histogram Bins
  DATA_TYPE: CDF_UINT2
  FORMAT: I4
  LABLAXIS: No. of bins
  UNITS: ' '
  VALIDMIN: 30
  VALIDMAX: 3600
  FILLVAL: 65535
  SCALETYP: linear
exposure_times:
  <<: *primary_data_variable
  NAME: exposure_times
  CATDESC: Exposure times for histogram bins for observational day
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Exposure Time Per Bin
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F7.2
  LABLAXIS: Bin exposure
  UNITS: s
  VALIDMIN: 0.0
  VALIDMAX: 9000.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  SCALEMIN: 0
  SCALEMAX: 9000
spin_angle:
  NAME: spin_angle
  CATDESC: Spin angle (measured from north) for bin centers
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  RECORD_VARYING: RV
  FIELDNAM: Spin Angle For Bin Centers
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F7.3
  LABLAXIS: Spin angle
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  DELTA_PLUS_VAR: spin_angle_delta
  DELTA_MINUS_VAR: spin_angle_delta
  SI_CONVERSION: 1.745329e-2>radians
spin_angle_delta:
  NAME: spin_angle_delta
  CATDESC: Half width of spin angle bin (spin-angle bin delta)
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  RECORD_VARYING: RV
  FIELDNAM: Half Width Of Spin Angle Bin
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F5.3
  LABLAXIS: Half-bin width
  UNITS: degrees
  VALIDMIN: 0.05
  VALIDMAX: 6.0
  FILLVAL: -1.000000e+31
  SCALETYP: linear
  SI_CONVERSION: 1.745329e-2>radians
ecliptic_lat:
  <<: *primary_support_data
  NAME: ecliptic_lat
  CATDESC: Ecliptic latitudes of bin centers
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Ecliptic Latitudes Of Bins
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F7.3
  LABLAXIS: Bin lat
  UNITS: degrees
  VALIDMIN: -90.0
  VALIDMAX: 90.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  SCALEMIN: -90.0
  SCALEMAX: 90.0
  SI_CONVERSION: 1.745329e-2>radians
ecliptic_lon:
  <<: *primary_support_data
  NAME: ecliptic_lon
  CATDESC: Ecliptic longitudes of bin centers
  DEPEND_1: spin_angle
  DISPLAY_TYPE: spectrogram
  FIELDNAM: Ecliptic Longitudes Of Bins
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F7.3
  LABLAXIS: Bin lon
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  SCALEMIN: 0.0
  SCALEMAX: 360.0
  SI_CONVERSION: 1.745329e-2>radians
filter_temperature_average:
  <<: *support_data
  NAME: filter_temperature_average
  CATDESC: Filter temperature averaged over observational day
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Filter Temperature
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F6.2
  LABLAXIS: Temp
  UNITS: Celsius
  VALIDMIN: -30.0
  VALIDMAX: 60.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: filter_temperature_std_dev
  DELTA_MINUS_VAR: filter_temperature_std_dev
filter_temperature_std_dev:
  <<: *support_data
  NAME: filter_temperature_std_dev
  CATDESC: Standard deviation of filter temperature
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of Filter Temperature
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  LABLAXIS: Temp std dev
  UNITS: Celsius
  VALIDMIN: 0
  VALIDMAX: 90.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
hv_voltage_average:
  <<: *support_data
  NAME: hv_voltage_average
  CATDESC: CEM HV voltage averaged over observational day
  DISPLAY_TYPE: time_series
  FIELDNAM: Average HV Voltage
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F7.2
  LABLAXIS: HV
  UNITS: V
  VALIDMIN: 0.0
  VALIDMAX: 3500.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: hv_voltage_std_dev
  DELTA_MINUS_VAR: hv_voltage_std_dev
hv_voltage_std_dev:
  <<: *support_data
  NAME: hv_voltage_std_dev
  CATDESC: Standard deviation of CEM HV voltage
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of HV Voltage
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  LABLAXIS: HV std dev
  UNITS: V
  VALIDMIN: 0.0
  VALIDMAX: 3500.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
spin_period_average:
  <<: *support_data
  NAME: spin_period_average
  CATDESC: Spin period averaged over observational day
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Spin Period
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F9.6
  LABLAXIS: Period
  UNITS: s
  VALIDMIN: 14.6
  VALIDMAX: 15.4
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: spin_period_std_dev
  DELTA_MINUS_VAR: spin_period_std_dev
spin_period_std_dev:
  <<: *support_data
  NAME: spin_period_std_dev
  CATDESC: Standard deviation of spin period
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of Spin Period
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  LABLAXIS: Period std dev
  UNITS: s
  VALIDMIN: 0.0
  VALIDMAX: 9.9
  FILLVAL: -1.000000E+31
  SCALETYP: linear
spin_period_ground_average:
  <<: *support_data
  NAME: spin_period_ground_average
  CATDESC: Spin period (ground processing) averaged over observational day
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Spin Period (Ground)
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F9.6
  LABLAXIS: Period
  UNITS: s
  VALIDMIN: 14.6
  VALIDMAX: 15.4
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: spin_period_ground_std_dev
  DELTA_MINUS_VAR: spin_period_ground_std_dev
spin_period_ground_std_dev:
  <<: *support_data
  NAME: spin_period_ground_std_dev
  CATDESC: Standard deviation of spin period (ground processing)
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of Spin Period (Ground)
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  LABLAXIS: Period std dev
  UNITS: s
  VALIDMIN: 0.0
  VALIDMAX: 9.9
  FILLVAL: -1.000000E+31
  SCALETYP: linear
pulse_length_average:
  <<: *support_data
  NAME: pulse_length_average
  CATDESC: Pulse length averaged over observational day
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Pulse Length
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F5.2
  LABLAXIS: Pulse len
  UNITS: us
  VALIDMIN: 0.0
  VALIDMAX: 12.75
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: pulse_length_std_dev
  DELTA_MINUS_VAR: pulse_length_std_dev
  SI_CONVERSION: 1.0e-6>s
pulse_length_std_dev:
  <<: *support_data
  NAME: pulse_length_std_dev
  CATDESC: Standard deviation of pulse length
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of Pulse Length
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  LABLAXIS: Pulse std dev
  UNITS: us
  VALIDMIN: 0.0
  VALIDMAX: 12.75
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  SI_CONVERSION: 1.0e-6>s
position_angle_offset_average:
  <<: *support_data
  NAME: position_angle_offset_average
  CATDESC: Position angle offset averaged over observational day
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Position Angle Offset
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F10.6
  LABLAXIS: Offset angle
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  DELTA_PLUS_VAR: position_angle_offset_std_dev
  DELTA_MINUS_VAR: position_angle_offset_std_dev
  SI_CONVERSION: 1.745329e-2>radians
position_angle_offset_std_dev:
  <<: *support_data
  NAME: position_angle_offset_std_dev
  CATDESC: Standard deviation of position angle offset
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of Position Angle Offset
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  LABLAXIS: Offset std dev
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0
  FILLVAL: -1.000000E+31
  SCALETYP: linear
  SI_CONVERSION: 1.745329e-2>radians
lon_lat:
  NAME: lon_lat
  CATDESC: Component index for ecliptic longitude and latitude
  VAR_TYPE: support_data
  RECORD_VARYING: NRV
  DISPLAY_TYPE: no_plot
  FIELDNAM: Longitude Latitude
  DATA_TYPE: CDF_INT1
  FORMAT: I1
  LABLAXIS: lon_lat
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 1
  FILLVAL: -128
  SCALETYP: linear
lon_lat_labels:
  <<: *metadata_variable
  NAME: lon_lat_labels
  CATDESC: Label names for ecliptic longitude and latitude
  FIELDNAM: Longitude Latitude Labels
  FORMAT: A3
  FILLVAL: ' '
spin_axis_orientation_average:
  <<: *primary_support_data
  NAME: spin_axis_orientation_average
  CATDESC: Spin axis pointing averaged over observational day (ecliptic lon and lat)
  DEPEND_1: lon_lat
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Spin Axis Pointing
  DATA_TYPE: CDF_DOUBLE
  FORMAT: F7.3
  UNITS: degrees
  VALIDMIN: -90.0
  VALIDMAX: 360.0
  FILLVAL: -1.00E+31
  LABL_PTR_1: lon_lat_labels
  SCALETYP: linear
  DELTA_PLUS_VAR: spin_axis_orientation_std_dev
  DELTA_MINUS_VAR: spin_axis_orientation_std_dev
  SI_CONVERSION: 1.745329e-2>radians
  LABLAXIS: Spin ax avg
spin_axis_orientation_std_dev:
  <<: *support_data
  NAME: spin_axis_orientation_std_dev
  CATDESC: Standard deviation of spin axis pointing
  DISPLAY_TYPE: time_series
  DEPEND_1: lon_lat
  FIELDNAM: Std Dev Of Spin Axis Pointing
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  UNITS: degrees
  VALIDMIN: 0.0
  VALIDMAX: 360.0
  FILLVAL: -1.00E+31
  LABL_PTR_1: lon_lat_labels
  SCALETYP: linear
  SI_CONVERSION: 1.745329e-2>radians
  LABLAXIS: Spin ax std dev
x_y_z:
  CATDESC: Component index for cartesian ecliptic coordinates
  NAME: x_y_z
  VAR_TYPE: support_data
  DISPLAY_TYPE: no_plot
  RECORD_VARYING: NRV
  DATA_TYPE: CDF_INT1
  FIELDNAM: X Y Z
  FORMAT: I1
  LABLAXIS: x_y_z
  UNITS: ' '
  VALIDMIN: 0
  VALIDMAX: 2
  FILLVAL: -128
  SCALETYP: linear
x_y_z_labels:
  <<: *metadata_variable
  NAME: x_y_z_labels
  CATDESC: Label names for cartesian ecliptic coordinates
  FIELDNAM: X Y Z Labels
  FORMAT: A1
  FILLVAL: ' '
spacecraft_location_average:
  <<: *primary_support_data
  NAME: spacecraft_location_average
  CATDESC: Spacecraft location averaged over observational day (ecliptic frame)
  DEPEND_1: x_y_z
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Spacecraft Location
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E13.6
  UNITS: km
  VALIDMIN: -9.999999999E+8
  VALIDMAX: 9.999999999E+8
  FILLVAL: -1.000000E+31
  LABL_PTR_1: x_y_z_labels
  SCALETYP: linear
  DELTA_PLUS_VAR: spacecraft_location_std_dev
  DELTA_MINUS_VAR: spacecraft_location_std_dev
  SI_CONVERSION: 1.0e3>m
  LABLAXIS: Loc
spacecraft_location_std_dev:
  <<: *support_data
  NAME: spacecraft_location_std_dev
  CATDESC: Standard deviation of spacecraft location
  DEPEND_1: x_y_z
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of Spacecraft Location
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  UNITS: km
  VALIDMIN: 0.0e+6
  VALIDMAX: 15.0e+6
  FILLVAL: -1.000000E+31
  LABL_PTR_1: x_y_z_labels
  SCALETYP: linear
  SI_CONVERSION: 1.0e3>m
  LABLAXIS: Loc std dev
spacecraft_velocity_average:
  <<: *support_data
  NAME: spacecraft_velocity_average
  CATDESC: Spacecraft velocity averaged over observational day (ecliptic frame)
  DEPEND_1: x_y_z
  DISPLAY_TYPE: time_series
  FIELDNAM: Average Spacecraft Velocity
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E13.6
  UNITS: km/s
  VALIDMIN: -50.0
  VALIDMAX: 50.0
  FILLVAL: -1.00E+31
  LABL_PTR_1: x_y_z_labels
  SCALETYP: linear
  DELTA_PLUS_VAR: spacecraft_velocity_std_dev
  DELTA_MINUS_VAR: spacecraft_velocity_std_dev
  SI_CONVERSION: 1.0e3>m/s
  LABLAXIS: Vsc
spacecraft_velocity_std_dev:
  <<: *support_data
  NAME: spacecraft_velocity_std_dev
  CATDESC: Standard deviation of spacecraft velocity
  DEPEND_1: x_y_z
  DISPLAY_TYPE: time_series
  FIELDNAM: Std Dev Of Spacecraft Velocity
  DATA_TYPE: CDF_DOUBLE
  FORMAT: E9.3
  UNITS: km/s
  VALIDMIN: 0.0
  VALIDMAX: 9.9
  FILLVAL: -1.000000E+31
  LABL_PTR_1: x_y_z_labels
  SCALETYP: linear
  SI_CONVERSION: 1.0e3>m/s
  LABLAXIS: Vsc std dev